### ISSUE TITLE
undefined method rebuild when tapping homebrew/php

### ISSUE THREAD

**Issue by lferro9000** [Homebrew/homebrew-php#3545] opened 2016-08-26 13:59 UTC
## Description

Undefined method rebuild when tapping homebrew/php

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.10.4
**Homebrew Version:**   | Homebrew 0.9.9 (git revision 0c6e30; last commit 2016-08-10)
**PHP Version in use:** | PHP stock-apple
**Xcode Version:**      | xcode 6.4 with command line tools installed

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix

**Output of php -v:**
PHP 5.5.24 (cli) (built: May 19 2015 10:10:05) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Build logs:**

$>brew tap homebrew/php

Cloning into '/usr/local/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 642, done.
remote: Compressing objects: 100% (395/395), done.
remote: Total 642 (delta 345), reused 499 (delta 245), pack-reused 0
Receiving objects: 100% (642/642), 303.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (345/345), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/arcanist.rb
undefined method `rebuild' for #<BottleSpecification:0x007fe5e9826fc8>

[... all formulas generate the same error ...]

Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/wp-cli.rb
undefined method `rebuild' for #<BottleSpecification:0x007fe5edadbd00>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/xdebug-osx.rb
undefined method `rebuild' for #<BottleSpecification:0x007fe5edb52680>
Error: Cannot tap homebrew/php: invalid syntax in tap!

Just as context, this is an jenkins agent machine which can't have xcode / command line tools updated as they are used on that specific version to compile and sign mac/ios software.

**Comment by lferro9000** [comment] 2016-08-26 14:06
This is related with:

https://github.com/Homebrew/homebrew-php/pull/3542

**Comment by javian** [comment] 2016-08-26 16:24
@lferro9000 can you confirm that this also happends after a recent `brew update` since the commit that I think caused this was reverted

**Comment by HiCodin** [comment] 2016-08-27 11:05
seems like the issue is gone after updating home brew. so i think the issue is fixed ?

**Comment by javian** [comment] 2016-08-27 14:12
@HiCodin I believe so but I can't verify it

**Comment by DomT4** [comment] 2016-08-27 15:50
@javian https://github.com/Homebrew/brew/pull/825 (now merged) should help reduce how often you run into this in future pretty drastically.

**Comment by javian** [comment] 2016-08-27 19:25
Thanks @DomT4 ! On that note I'm going to close the issue assuming that the upstream PR has made this go away.

**Closed by javian** 2016-08-27 19:25 UTC
Labels: External Issue

**Comment by luzbos** [comment] 2016-11-29 04:07
brew update  is ok!  thanks.
