### ISSUE TITLE
PHP56 can't launch as root, with nginx 500 Internal Server Error?

### ISSUE THREAD

**Issue by chinanoahli** [Homebrew/homebrew-php#2709] opened 2015-12-29 08:44 UTC
I am still using php56+nginx/1.8.0 at OS X 10.11.2.

My page documents locate in `/usr/local/var/www` `drwxr-xr-x joshua:admin`
My nginx configure is [nginx.conf](https://gist.github.com/chinanoahli/8c0f75319e8ef0606381) and my php and php-fpm configure is [this file](https://gist.github.com/chinanoahli/d91acaa041b2c5635bdd)

and I find I can use wordpress(/usr/local/var/www/wordpress/) and phpmyadmin(/usr/local/var/www/phpMyAdmin-4.5.2/) perfectly, but not anchor(/usr/local/var/www/anchor) and Drupal(/usr/local/var/www/drupal/), I can access the home page of anchor and drupal, but when I click a link, it will shows 500 error.

I get this log from the php-fpm

    NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
    NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root

I already tried make the php-fpm.conf file like this

    user = joshua
    group = admin
    listen.owner = joshua
    listen.group = admin

but nothing happened, and the error log still the **same**.

Is there any ways can make it work when FPM is **not** running as root, because I dont realy want FPM run as root.

I tried a lot, but I still don't know how to launch PHP-FPM as root. Normally, if the **/Library/LaunchDaemons/homebrew.mxcl.php56.plist** owner by root the PHP-FPM should launch as root, but it still launch as normal user on my mac. I really don't know how to get it work. My **homebrew.mxcl.mariadb.plist** and **homebrew.mxcl.nginx.plist** can launch as root by changing this two files to onwer by root.

**Comment by rspeed** [comment] 2016-01-23 03:45
It doesn't sound to me like that warning is related, since everything should be running as your user, and you have read access to the files. A 500 error could indicate that nginx wasn't able to communicate with php-fpm at all. Take a look at the nginx error log. You might have enable in `/usr/local/etc/nginx/nginx.conf`.

**Comment by rspeed** [comment] 2016-01-23 03:48
Though for future reference, Launch Agents always are spawned by a separate launchd process which is run as the user who is currently logged in. Only Launch Daemons are run (by default) as root.

**Comment by chinanoahli** [comment] 2016-01-23 08:39
@rspeed I checked the error log of the nginx, and I got [this](https://gist.github.com/chinanoahli/8c0f75319e8ef0606381#file-nginx-error-log). This is the first time I use nginx, I really do not know how to write a correct configure file for the nginx. I tried a lot, now I can got wordpress work, but there must be something wrong on it and I don't where went wrong, and I don't know how to fix it.

**Comment by rspeed** [comment] 2016-01-23 14:41
That's definitely not being caused by PHP. If I had to guess, it could be because of the duplicate `try_files` directives. One in the `server` scope and the other in the `location` scope.

**Comment by javian** [comment] 2016-08-10 17:18
@chinanoahli I don't know if we can help you further with this in here. Did you manage to resolve the issue ?

**Comment by josegonzalez** [comment] 2016-09-25 08:59
Closing as there hasn't been any update in 2+ weeks.

**Closed by josegonzalez** 2016-09-25 08:59 UTC
Labels: External Issue
