### ISSUE TITLE
Upgrade to php 5.6.24 : cannot run apxs

### ISSUE THREAD

**Issue by jblaise** [Homebrew/homebrew-php#3397] opened 2016-07-27 14:46 UTC
## Description
when running a brew upgrade, it failed when doing the configure.

## Context and Logs
i was upgrading 4 outdated packages:
homebrew/php/composer 1.2.0, homebrew/php/php56 5.6.24, homebrew/php/php56-intl 5.6.24_1, homebrew/php/php56-mcrypt 5.6.24

[Here](https://gist.github.com/jblaise/1927b19fcae6de442ff657a42237b15a) is the log.

Parameter | Value
--------- | ------------------
**OS X Version:**       |  10.9.5
**Homebrew Version:**   | 0.9.9
**PHP Version in use:** | 5.6.23

## Solution
The problem wasn't hard to solve but this error was surprising (as I didn't do anything in apr folder).

```bash
cd /usr/local/Cellar/apr
ln -s 1.5.2_1 1.5.2
```

**Comment by javian** [comment] 2016-08-18 18:51
Thanks for the report. Not sure what could be causing this issue. It also look weird that a softlink in the Cellar would solve the issue. We would need to see more of the logs to have any type of clue of what could be going on here.

**Comment by dorapen** [comment] 2016-08-22 12:36
I had the exactly same problem while upgrade php 7.0.9 to 7.0.10. Solution by @jblaise fixed the issue as well. Here's my log:

`Last 15 lines from /Users/<USER>/Library/Logs/Homebrew/php70/01.configure:
checking for pthreads_lib... 

Configuring SAPI modules
checking for Apache 2.0 handler-module support via DSO through APXS... 

Sorry, I cannot run apxs.  Possible reasons follow:

1. Perl is not installed
2. apxs was not found. Try to pass the path using --with-apxs2=/path/to/apxs
3. Apache was not built using --enable-so (the apxs usage page is displayed)

The output of /usr/local/bin/apxs follows:
apxs:Error: /usr/local/Cellar/apr/1.5.2/libexec/bin/apr-1-config not found!.

configure: error: Aborting

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

These open issues may also help:
php70-dbase  https://github.com/Homebrew/homebrew-php/issues/3508
Add php70-zmq formula https://github.com/Homebrew/homebrew-php/pull/3474
Install PHP70: Incompatible library version https://github.com/Homebrew/homebrew-php/issues/3444
php70-imagick has warnings https://github.com/Homebrew/homebrew-php/issues/2766
brew install php70-redis https://github.com/Homebrew/homebrew-php/issues/2762
Allow --enable-redis-igbinary for php70-redis https://github.com/Homebrew/homebrew-php/pull/3473
Update to the latest php71, php70 and php56 https://github.com/Homebrew/homebrew-php/issues/3502
Add head formula for php70-uploadprogress https://github.com/Homebrew/homebrew-php/pull/3178`

**Comment by jblaise** [comment] 2016-08-22 20:41
@javian I don't either know how to reproduce this case. I just posted it to provide help for those who may encounter the same issue as I did not see anything close to this.

**Comment by javian** [comment] 2016-08-22 22:28
This is also reported in the homebrew-apache tap https://github.com/Homebrew/homebrew-apache/issues/126

**Comment by javian** [comment] 2016-08-23 05:51
I the problem is found now and all we need is a bottle update of the right Formulas and we should be able to close this.

**Comment by javian** [comment] 2016-09-02 21:07
This should have been correct now after updating apr, apr-util and the httpd packages.

**Closed by javian** 2016-09-02 21:07 UTC
Labels: 10.9, Needs Info
