### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _mmc_queue_pop

### ISSUE THREAD

**Issue by rkoberg** [Homebrew/homebrew-php#1366] opened 2014-10-09 18:53 UTC
After installing the devel version of php53-memcache php is not working anymore with the error in the title. This thread contains the answer, 

> As David mentioned in the comments, when building the memcache plugin, NOT memcached itself, you have to add run configure like this:
> 
> `MACOSX_DEPLOYMENT_TARGET=10.7 CFLAGS='-fgnu89-inline' LDFLAGS='-fgnu89-inline' CXXFLAGS='-fgnu89-inline' ./configure`

but I can't get it to work. I have tried adding to the formula like so:

```
    safe_phpize
    system "MACOSX_DEPLOYMENT_TARGET=10.7 CFLAGS='-fgnu89-inline' LDFLAGS='-fgnu89-inline' CXXFLAGS='-fgnu89-inline' ./configure", "--prefix=#{prefix}",
                          phpconfig
    system "make"
```

But that failed on install. I tried pasting `MACOSX_DEPLOYMENT_TARGET=10.7 CFLAGS='-fgnu89-inline' LDFLAGS='-fgnu89-inline' CXXFLAGS='-fgnu89-inline'` in the Terminal before running

```
$ brew install --devel php53-memcache
```

But that didn't work as I still get the error in the title.

Any ideas how to fix?

Some details:
OS X 10.9.5

```
$ otool -L /usr/local/Cellar/php53-memcache/3.0.8/memcache.so 
/usr/local/Cellar/php53-memcache/3.0.8/memcache.so:
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

I checked the options, but did not see anything that looks like what I need?

```
$ brew options php53-memcache
--without-config-file
    Do not install extension config file
--without-homebrew-php
    Ignore homebrew PHP and use default instead
--devel
    install development version 3.0.8
--HEAD
    install HEAD version
```

**Comment by alanthing** [comment] 2015-02-24 21:05
I'm going to close this since there have been a lot of changes in recent weeks. Please re-open if unable to resolve.

**Comment by PalliDotCom** [comment] 2015-07-27 09:39
I'm having the same issue.

**Comment by steel-track** [comment] 2015-10-14 20:04
Simply adding ENV variables for the CFLAGS worked for me:

```
def install
    Dir.chdir "memcache-#{version}" unless build.head?

    ENV.universal_binary if build.universal?

    ENV['CFLAGS'] = '-fgnu89-inline'
    ENV['LDFLAGS'] = '-fgnu89-inline'
    ENV['CXXFLAGS'] = '-fgnu89-inline'

    safe_phpize
    system "./configure", "--prefix=#{prefix}",
                          phpconfig
    system "make"
    prefix.install "modules/memcache.so"
    write_config_file if build.with? "config-file"
  end
```

**Comment by jeroenseegers** [comment] 2016-01-15 10:17
The above also worked for me after encountering numerous errors in the form of:
```
dyld: lazy symbol binding failed: Symbol not found: _mmc_queue_free
  Referenced from: /usr/local/opt/php56-memcache/memcache.so
  Expected in: flat namespace
```

**Comment by JohnAlbin** [comment] 2016-02-12 16:29
The changes that @steel-track posted fixed the issue I was having, which was the error message that @jeroenseegers posted above.

@alanthing Can we re-open this now?

**Comment by glassdimly** [comment] 2016-05-04 23:44
I can confirm the errors and the fix posted above by @steel-track!

**Comment by javian** [comment] 2016-05-18 19:55
Reopened on request. I've only seen php53 and php56 mentioned in this issue but I'm assuming the fix is for all the posted php version that has a memcache module ? Feel free to contribute a PR in the meantime.

**Comment by josegonzalez** [comment] 2016-09-25 08:41
Does anyone want to contribute this fix as a pull request to homebrew-php? If not, the Issue Closing Fairy™ (me) will close this in two weeks.

**Closed** 2016-10-27 19:58 UTC
Labels: 2 Week Notice
