### ISSUE TITLE
failed install php7

### ISSUE THREAD

**Issue by JyHu** [Homebrew/homebrew-php#3266] opened 2016-06-14 07:42 UTC
## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | _10.11.5_
**Homebrew Version:**   | _0.9.5_
**PHP Version in use:** | _5.5.34_
**Xcode Version:**      | _7 && 8.0beta_

**Output of gcc -v:**
```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**
```
php -v
PHP 5.5.34 (cli) (built: Apr 22 2016 19:16:58) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

**Build logs:** 
```
brew gist-logs my-formula
Error: No available formula for my-formula 
```

**Install log:**
```
brew install php70
==> Installing php70 from josegonzalez/homebrew-php
==> Downloading https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/php70-7.0.4.el_capitan.bottle.12.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php70"
Download failed: https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/php70-7.0.4.el_capitan.bottle.12.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://php.net/get/php-7.0.4.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php70-7.0.4
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.4 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.0 --with-config-file-path=/usr/local/
Last 15 lines from /Users/JyHu/Library/Logs/Homebrew/php70/01.configure:
checking for OpenSSL support... yes
checking for Kerberos support... /usr
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.8
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/josegonzalez/homebrew-php/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:436:in `open'
	from /usr/local/Library/Homebrew/utils.rb:466:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:498:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:209:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:205:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:248:in `dump'
	from /usr/local/Library/brew.rb:160:in `rescue in <main>'
	from /usr/local/Library/brew.rb:67:in `<main>'
```

**Comment by javian** [comment] 2016-06-14 20:53
You are missing the libz header files. You need to run `xcode-select --install` to install them. Sometimes they disappear for currently unknown reasons but likely related to an upgrade to El Capitan (unconfirmed).

**Comment by javian** [comment] 2016-06-16 04:50
You also need to `brew untap josegonzalez/php` and then `brew tap homebrew/homebrew-php` so that you can download the bottles.

**Comment by javian** [comment] 2016-06-22 20:13
Closing issue due to no answer. Feel free to reopen it if you have further questions.

**Closed by javian** 2016-06-22 20:13 UTC
