### ISSUE TITLE
Apache fails to start after update from 5.6.x to 5.6.20 symbol not found: _ldap_control_find

### ISSUE THREAD

**Issue by Kyslik** [Homebrew/homebrew-php#3074] opened 2016-04-06 21:23 UTC
I have just run `brew upgrade` command, after building, apache is not starting.

OS X: **Yosemite 10.10.5**

`$ apachectl configtest`
>httpd: Syntax error on line 169 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php56/libexec/apache2/libphp5.so

http://stackoverflow.com/questions/36415854/httpd-libphp5-so-ldap-error

**Comment by gapple** [comment] 2016-04-06 21:49
This looks like the same issue as #3073

**Comment by Kyslik** [comment] 2016-04-06 21:54
Yes it looks like same, just different PHP version.

**Comment by javian** [comment] 2016-04-08 05:57
I would say close this issue and post a note in the other one or just subscribe to it so you are notified of any updates and that we are aware that it's affected more then php7.

**Comment by javian** [comment] 2016-04-08 05:58
Would also be good to know if you are not using Yosemite since that's the os of the OP in the other issue.

**Comment by Kyslik** [comment] 2016-04-08 13:42
Yes I am on Yosemite 10.10.5.

**Comment by curiouscrusher** [comment] 2016-04-14 19:20
Just wanted to jump in and confirm this has affected my stack as well after running brew upgrade today – OSX v10.10.5 (14F1713)
I've tried both php56 and php70 with no difference – 

`httpd: Syntax error on line 174 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php70/libexec/apache2/libphp7.so into server: dlopen(/usr/local/opt/php70/libexec/apache2/libphp7.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/opt/php70/libexec/apache2/libphp7.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php70/libexec/apache2/libphp7.so`

`httpd: Syntax error on line 172 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php56/libexec/apache2/libphp5.so`

**Comment by ryanilg** [comment] 2016-04-21 15:55
Same issue here. Also 10.10.5.

**Comment by javian** [comment] 2016-04-27 16:23
The bottle has now been regenerated - can you check if the problem is resolved now ?

**Comment by Kyslik** [comment] 2016-04-27 18:05
I think error is still present 
I did:

```
brew uninstall php56
brew cleanup
brew install php56
```
and `apachectl configtest` gives same error as in first post:

>httpd: Syntax error on line 169 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php56/libexec/apache2/libphp5.so

**Comment by javian** [comment] 2016-04-28 04:57
@Kyslik thanks for the feedback. I assume you ran `brew update` before installing again ?

**Comment by Kyslik** [comment] 2016-04-28 06:43
I tested now (with `brew update` in between) and same error; (yesterday I think brew downloaded "new" bottle because I did `brew cleanup`)

**Comment by ajcdev** [comment] 2016-04-29 07:48
Yeah, it's work (php 5.6.21) on yosemite :

`brew uninstall php56
brew cleanup
brew install php56`

Thx

**Comment by Kyslik** [comment] 2016-04-30 08:52
@ajcdev if you previously installed php56 using `$ brew install php56 --without-ldap` then new version is installed with same configuration (I assume).

Today I did clean install of php56 (uninstalled 5.6.20) and installed without any flags ($ brew install php56) and `$ apachectl configtest` errors out

```
🍺  /usr/local/Cellar/php56/5.6.21: 331 files, 49.0M
 ~  apachectl configtest
httpd: Syntax error on line 169 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php56/libexec/apache2/libphp5.so
```

**Comment by 3rdLOF** [comment] 2016-05-05 11:28
Having the same problem on a speaking new Yosemite install. Did the normal reinstall, the build-from-source reinstalled. cleanup and the works. Nothing smells to shake it off.

**Comment by ajcdev** [comment] 2016-05-09 06:26
Sorry, I spoken too quickly. Finally PHP5.6 does not work.

**Comment by ajcdev** [comment] 2016-05-17 15:18
I upgraded Yosemite to El Capitan and now I have no more problem with PHP56 and PHP7

**Comment by javian** [comment] 2016-05-24 21:10
I've now gotten my hands on a Yosemite system to see this first hand. The bottle as everyone has stated is not working on 10.10.5 in combination with Apache. If built from source I got it to work (not sure why it didn't work for you @3rdLOF ) and I did not have to remove the ldap module.

This is somehow related to the build process and bottle generation and I'm trying to figure out if there's a way to work around it in the meantime.

**Comment by Jeroen-Sen** [comment] 2016-06-02 09:15
Hi,
Luckily I don't rely on ldapin php, so working for me:

`brew uninstall php56` (and all other extensions like opcode, intl and xdebug)
`brew cleanup`
`brew update` (just to be absolutely sure)
`brew install php56 --without-ldap` (and all other extensions)

**Comment by thrallthink** [comment] 2016-06-29 12:53
Thanks Jeroen-Sen,
This command solved my problem:
brew install php56 --without-ldap (and all other extensions)

I was getting this issue: 
httpd: Syntax error on line 171 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/Cellar/php56/5.6.23/libexec/apache2/libphp5.so into server: dlopen(/usr/local/Cellar/php56/5.6.23/libexec/apache2/libphp5.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/Cellar/php56/5.6.23/libexec/apache2/libphp5.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/Cellar/php56/5.6.23/libexec/apache2/libphp5.so

**Comment by abhinavkumar940** [comment] 2016-09-09 03:23
Just wanted to confirm that `--without-ldap` flag worked for me on 10.10.5

**Comment by josegonzalez** [comment] 2016-09-25 08:32
Closing this issue as duplicate of #3073. Lets keep all discussion on the same issues in one place.

**Closed by josegonzalez** 2016-09-25 08:32 UTC
Labels: 10.10, php56

**Comment by wordica** [comment] 2017-09-26 16:40
If someone had problem after update OS X, check version of php, and if PHP is 7 then do not use old apache config. For PHP apache have LoadModule php7_module libexec/apache2/libphp7.so

**Comment by Chienle** [comment] 2017-09-26 17:37
I have above issue after update to macos 10.130 with php 7.1
