### ISSUE TITLE
Enabling php70-opcache

### ISSUE THREAD

**Issue by MaciejJanyska** [Homebrew/homebrew-php#3619] opened 2016-09-25 19:55 UTC
## Description

The php70-opcache installation was successful but it wasn't enabled. In ~~`php.ini`~~ `phpinfo()` there is a Configure Command: `--disable-opcache` (if it matters). Nothing else. Any solution?

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12
**Homebrew Version:**   | 1.0.4
**PHP Version in use:** | 7.0.11
**Xcode Version:**      | 8.0

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP 7.0.11 (cli) (built: Sep 23 2016 22:14:34) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by javian** [comment] 2016-09-25 20:04
@MaciejJanyska thanks for the report. It shouldn't touch php.ini but rather place a file in `/usr/local/etc/php/7.0/conf.d` for each extension so unless something else is wrong then check there.

**Comment by javian** [comment] 2016-09-26 20:35
This seems to be caused by a bug in brew and we need to regenerate the bottle for opcache and it should work as expected after that. In the meantime you can install it from source with `brew install -s php70-opcache` and that should create the config file for you as well.

**Comment by MaciejJanyska** [comment] 2016-09-26 20:46
Unfortunately `ext-opcache.ini` wasn't created but installing from source do the trick. Thanks @javian !

**Comment by javian** [comment] 2016-10-01 06:03
The bottle containing the fix has now been merged in #3637

**Closed by javian** 2016-10-01 06:03 UTC
