### ISSUE TITLE
Unable to load dynamic library error with all versions of PHP on Sierra

### ISSUE THREAD

**Issue by forestlovewood** [Homebrew/homebrew-php#4011] opened 2017-02-25 17:06 UTC
## Description

When I install PHP using Homebrew, any extensions that I attempt to load (including the core extensions such as `mysqli` and `gd2`) throw an `Unable to load dynamic library` error during any use.

The error thrown is as follows:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_mysqli.dll' - dlopen(/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_mysqli.dll, 9): image not found in Unknown on line 0
```

The folder referenced, `/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012`, does not exist. The command used for installation was `brew install homebrew/php/php70 --with-httpd24 --with-pear`. I also attempted without the `--with-pear` flag.

I note that while the error refers to DLL files for some reason, changing these to SO files in the php.ini file does not resolve the problem, as the files still do not exist anywhere on the system.

I have now attempted this installation on a clean macOS system, trying PHP 5.6 first and then PHP 7.0. Both experience the same issue.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | macOS Sierra 10.12.3
**Homebrew Version:**   | Homebrew 1.1.10
**PHP Version in use:** | 7.0.15
**Xcode Version:**      | Latest

**Output of gcc -v:**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Output of php -v:**
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_mysqli.dll' - dlopen(/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_mysqli.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_mysqli.dll' - dlopen(/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_mysqli.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_sqlite3.dll' - dlopen(/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_sqlite3.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_sqlite3.dll' - dlopen(/usr/local/Cellar/php70/7.0.15_8/lib/php/extensions/no-debug-non-zts-20151012/php_sqlite3.dll, 9): image not found in Unknown on line 0
PHP 7.0.15 (cli) (built: Feb 25 2017 16:51:58) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

**Build logs:** [https://gist.github.com/9cc77312bdb96d8a6454ccc30e5e123a](https://gist.github.com/9cc77312bdb96d8a6454ccc30e5e123a)

**Comment by javian** [comment] 2017-02-27 21:22
Since you are on a mac it should not even use dll so I don't have a clue where the references to them came from. Can you do `grep -Rl no-debug-non-zts-20151012 /usr/local/etc/php/7.0` to see which config files that contains the reference ?

**Comment by forestlovewood** [comment] 2017-02-27 22:26
I ran `grep -Rl no-debug-non-zts-20151012 /usr/local/etc/php/7.0` and there was literally no output at all. It's bizarre. I just tried another clean installation for this - installed macOS Sierra 10.12.3, installed Xcode 8.2.1, installed command line tools 8.2.1, installed Gomebrew 1.1.10, then followed the instructions to the letter on the README for this repo to install PHP 7.0, and it had the exact same issue.

**Comment by FrancisVarga** [comment] 2017-03-10 11:34
Have the same problem everything explode when i installed php70 all modules got screwed up

**Comment by FrancisVarga** [comment] 2017-03-10 11:52
Ok all modules has to be build from source... Thanks

**Comment by javian** [comment] 2017-03-11 10:49
@FrancisVarga that's a completely different issue its not related to this.

**Comment by javian** [comment] 2017-03-11 10:53
@forestlovewood could you do `php -i | grep php.ini` to check which path php uses to check for the ini file ?

**Comment by forestlovewood** [comment] 2017-03-13 17:48
@javian it uses `/usr/local/etc/php/5.6` as the location and `/usr/local/etc/php/5.6/php.ini` as the file.

**Comment by javian** [comment] 2017-03-22 22:31
@forestlovewood that looks very strange since you are running php 7. Now that that is clear though what does `grep -Rl no-debug-non-zts-20151012 /usr/local/etc/php/5.6` output ?

**Comment by htollefsen** [comment] 2017-04-27 08:47
I had this same issue on Sierra 10.12.3, Homebrew 1.1.13, xcode 8.3.2. Quickfixed it by reinstalling the module: `brew remove php71-imagick && brew install php71-imagick`.

**Comment by nkuhan** [comment] 2017-05-04 07:12
`brew uninstall --ignore-dependencies php56 `
then close and open the terminal works for me for the version 5.6

**Comment by justnealpatel** [comment] 2017-05-25 18:47
Has anyone found a fix to this yet? I'm running PHP 5.6.30, Sierra 10.12.4, and this same issue still occurs. I've tried all the above solutions.

This is what I get specifically.
```bash
php -v

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/php_openssl.dll' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20131226/php_openssl.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/php_openssl.dll' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20131226/php_openssl.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/php_pdo_pgsql.dll' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20131226/php_pdo_pgsql.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/php_pdo_pgsql.dll' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20131226/php_pdo_pgsql.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/php_pgsql.dll' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20131226/php_pgsql.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/php_pgsql.dll' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20131226/php_pgsql.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/pgsql.so' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20131226/pgsql.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/pgsql.so' - dlopen(/usr/lib/php/extensions/no-debug-non-zts-20131226/pgsql.so, 9): image not found in Unknown on line 0
PHP 5.6.30 (cli) (built: Feb  7 2017 16:06:52) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

I even tried to supply the path to the extension yet it still doesn't find it.

**Comment by javian** [comment] 2017-05-26 06:42
@justnealpatel that's a different issue since you are trying to load extensions that comes with sierra and not the homebrew ones. Open a seperate issue if you keep having problems.

**Comment by daniel-zahariev** [comment] 2017-06-06 00:07
I just experienced the same issue and removing and installing again the gcloud component `app-engine-php-darwin` fixed this for me.

**Comment by josegonzalez** [comment] 2017-06-06 00:47
@daniel-zahariev this repository isn't for google cloud, but for managing php installations on OS X.

**Comment by ActionScripted** [comment] 2017-07-18 15:22
I've had this happen on two systems.

It doesn't seem to matter which modules are used, either, it seems to have something to do with how they're being loaded or referenced. When I remove all modules -- everything in `/usr/local/etc/php/7.0/conf.d` -- PHP works without issue and without reinstalling or reconfiguring.

**Comment by bytehead** [comment] 2017-09-14 16:39
Removing `brew uninstall php71-imagick` and install from source again `brew install --build-from-source php71-imagick` solved my problem.

**Comment by benjamincrozat** [comment] 2017-09-22 13:45
@bytehead Thanks a lot. :)
For those coming from Google, here is the copy/paste ready fix:
```bash
brew reinstall --build-from-source php71-imagick
```

**Comment by jbouhier** [comment] 2017-10-11 17:18
@bytehead @benjaminschulz Worked with php72 RC3 and brew package php72-libsodium (the new crypto lib replacing php-mcrypt). Thanks guys.

**Comment by tobiasz** [comment] 2017-10-17 06:53
`php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-igbinary/igbinary.so' - dlopen(/usr/local/opt/php71-igbinary/igbinary.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php71-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php71-igbinary/igbinary.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-igbinary/igbinary.so' - dlopen(/usr/local/opt/php71-igbinary/igbinary.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php71-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php71-igbinary/igbinary.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php71-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php71-intl/intl.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php71-intl/intl.so
  Expected in: flat namespace
 in /usr/local/opt/php71-intl/intl.so in Unknown on line 0
PHP Warning:  PHP Startup: mcrypt: Unable to initialize module
Module compiled with build ID=API20160303,NTS
PHP    compiled with build ID=API20160303,TS
These options need to match
 in Unknown on line 0

Warning: PHP Startup: mcrypt: Unable to initialize module
Module compiled with build ID=API20160303,NTS
PHP    compiled with build ID=API20160303,TS
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-mongodb/mongodb.so' - dlopen(/usr/local/opt/php71-mongodb/mongodb.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php71-mongodb/mongodb.so
  Expected in: flat namespace
 in /usr/local/opt/php71-mongodb/mongodb.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-mongodb/mongodb.so' - dlopen(/usr/local/opt/php71-mongodb/mongodb.so, 9): Symbol not found: _compiler_globals
  Referenced from: /usr/local/opt/php71-mongodb/mongodb.so
  Expected in: flat namespace
 in /usr/local/opt/php71-mongodb/mongodb.so in Unknown on line 0
PHP Warning:  Cannot load module 'redis' because required module 'igbinary' is not loaded in Unknown on line 0

Warning: Cannot load module 'redis' because required module 'igbinary' is not loaded in Unknown on line 0
`

fixed by reinstalling every module.

`brew reinstall --build-from-source`

**Comment by kwhat** [comment] 2017-10-20 22:24
This is a super annoying issue that keeps popping up.  Everytime I change any installed module, I get these errors.  This is definitely not the only bug report related to the problem.

**Comment by josegonzalez** [comment] 2017-10-20 22:31
@kwhat thanks for that. Any idea what the actual fix might be in this case?

**Comment by black-snow** [comment] 2017-10-26 13:37
I too just stumbled upon this. Nothing fancy here.
`homebrew/php/php56: stable 5.6.31 (bottled), HEAD`
`Built from source on 2017-09-14 at 12:44:51 with: --with-httpd24 --with-libmysql`

Error is the same:
> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.31_7/lib/php/extensions/no-debug-non-zts-20131226/php_mysql.dll' - dlopen(/usr/local/Cellar/php56/5.6.31_7/lib/php/extensions/no-debug-non-zts-20131226/php_mysql.dll, 9): image not found in Unknown on line 0

**Comment by javian** [comment] 2017-10-26 13:46
@black-snow you need to double check your php config. You should not try to load a dll on macOS =)

**Comment by javian** [comment] 2017-10-26 13:49
@kwhat are you running with thread safety on ?
```
Warning: PHP Startup: mcrypt: Unable to initialize module
Module compiled with build ID=API20160303,NTS
PHP    compiled with build ID=API20160303,TS
```
This error indicates that you use TS (Thread Safety) and the module is compiled with NTS (non-thread safety) which are not compatible with eachother. Since all modules are built with NTS and you update a module using a TS php binary then the update will need to be recompiled. This is a weakness is the current setup and not easily solved without duplicating all modules unless we don't bottle the formulas and for everyone to compile everything.

**Comment by black-snow** [comment] 2017-10-26 14:05
@javian I didn't touch any config. Homebrew must have screwed something up.
Error remains after reinstall.

**Comment by Drewson** [comment] 2017-11-07 19:24
@forestlovewood Did you ever find a fix to this? Nothing in these comments really helps eh...

**Comment by austinheap** [comment] 2017-11-09 07:26
`brew install [php71-intl|php71-mongodb|...] --build-from-source` works for me. macOS 10.13 here.

**Comment by SMillerDev** [comment] 2017-11-09 10:07
@Drewson maybe you can continue helping with the investigation that ended here https://github.com/Homebrew/homebrew-php/issues/4011#issuecomment-288560344

**Comment by RastoStric** [comment] 2017-11-20 13:51
Really nobody here to be able to solve it? I am having problems with php_mbstring:
```
php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.32_8/lib/php/extensions/no-debug-non-zts-20131226/php_mbstring.dll' - dlopen(/usr/local/Cellar/php56/5.6.32_8/lib/php/extensions/no-debug-non-zts-20131226/php_mbstring.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.32_8/lib/php/extensions/no-debug-non-zts-20131226/php_mbstring.dll' - dlopen(/usr/local/Cellar/php56/5.6.32_8/lib/php/extensions/no-debug-non-zts-20131226/php_mbstring.dll, 9): image not found in Unknown on line 0
PHP 5.6.32 (cli) (built: Nov 20 2017 14:40:19) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
I tried ` brew reinstall php56 --build-from-source --with-httpd` but the same result ☹️
macOS 10.13.1

**Comment by SMillerDev** [comment] 2017-11-20 14:07
@RastoStric maybe you can be the one that helps us solve this issue.  The investigation ended here https://github.com/Homebrew/homebrew-php/issues/4011#issuecomment-288560344 and is still waiting to be continued by someone who has this issue.

**Comment by forestlovewood** [comment] 2017-11-20 14:20
In my case, the solution to the issue has been to not enable any modules in the `php.ini` file. The modules, when installed using Homebrew, are integrated and enabled automatically without need for additional configuration. As such, none of the library files exist, because they don't need to, so attempting to reference them causes errors.

I'm not sure, though, that everyone else has the same cause for their issues. It's worth checking, though - make sure no extensions are linked in the `php.ini` and then check `phpinfo()` to see what extensions have been loaded.

**Comment by RastoStric** [comment] 2017-11-20 14:57
@forestlovewood Thank you very much, this finally worked! Exactly as you suggested I disabled mbstring `;extension=php_mbstring.dll` and the problem is gone! Your explanation seems to be reasonable.

@SMillerDev My problem has just been solved, thank you.

**Comment by fbricenho** [comment] 2017-11-22 16:42
@forestlovewood How do I make sure about that? first month using OSX

**Comment by SMillerDev** [comment] 2017-11-22 18:23
Seeing how the OP has found a solution for the issues, I'll be closing this issue.

**Closed by SMillerDev** 2017-11-22 18:23 UTC
