### ISSUE TITLE
Brew provides shell script as Composer executable, other tools expect a PHP script

### ISSUE THREAD

**Issue by bocharsky-bw** [Homebrew/homebrew-php#3590] opened 2016-09-20 09:36 UTC
## Description

Brew provides broken `composer.phar` file. It works in regular use, but does not work with Ansible. If I replace `/usr/local/Cellar/composer/1.2.1/libexec/composer` (which provided by Brew) with the original `composer.phar` downloaded with [these instuctions](https://getcomposer.org/download/) - then original Composer works fine with Ansible. So the problem only in `composer.phar` provided by Brew.
## Steps to reproduce:
1. `$ brew install ansible`
2. `$ brew install composer`
3. `$ ansible localhost -m composer -a "working_dir=./path-to-dir-with-valid-composer-json"` // it doesn't work, see logs below:
## Context and Logs

Output of `$ ansible localhost -m composer -a "working_dir=./path-to-dir-with-valid-composer-json"`:

```
Loaded callback minimal of type stdout, v2.0
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: victor
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474021242.83-74316657830341 `" && echo ansible-tmp-1474021242.83-74316657830341="` echo $HOME/.ansible/tmp/ansible-tmp-1474021242.83-74316657830341 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/5t/qb0jlm4x7g90bp__cnr1lybh0000gn/T/tmpLAYqVM TO /Users/victor/.ansible/tmp/ansible-tmp-1474021242.83-74316657830341/composer
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/victor/.ansible/tmp/ansible-tmp-1474021242.83-74316657830341/composer; rm -rf "/Users/victor/.ansible/tmp/ansible-tmp-1474021242.83-74316657830341/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/5t/qb0jlm4x7g90bp__cnr1lybh0000gn/T/ansible_a_ligN/ansible_module_composer.py", line 232, in <module>
    main()
  File "/var/folders/5t/qb0jlm4x7g90bp__cnr1lybh0000gn/T/ansible_a_ligN/ansible_module_composer.py", line 183, in main
    available_options = get_available_options(module=module, command=command)
  File "/var/folders/5t/qb0jlm4x7g90bp__cnr1lybh0000gn/T/ansible_a_ligN/ansible_module_composer.py", line 151, in get_available_options
    command_help_json = json.loads(out)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "composer"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/5t/qb0jlm4x7g90bp__cnr1lybh0000gn/T/ansible_a_ligN/ansible_module_composer.py\", line 232, in <module>\n    main()\n  File \"/var/folders/5t/qb0jlm4x7g90bp__cnr1lybh0000gn/T/ansible_a_ligN/ansible_module_composer.py\", line 183, in main\n    available_options = get_available_options(module=module, command=command)\n  File \"/var/folders/5t/qb0jlm4x7g90bp__cnr1lybh0000gn/T/ansible_a_ligN/ansible_module_composer.py\", line 151, in get_available_options\n    command_help_json = json.loads(out)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py\", line 338, in loads\n    return _default_decoder.decode(s)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py\", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py\", line 384, in raw_decode\n    raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

| Parameter | Value |
| --- | --- |
| **OS X Version:** | OS X El Capitan 10.11.6 |
| **Homebrew Version:** | Homebrew 0.9.9 (git revision f87e; last commit 2016-09-20) Homebrew/homebrew-core (git revision a530; last commit 2016-09-20) |
| **PHP Version in use:** | PHP 7.0.11 (cli) (built: Sep 16 2016 23:09:59) ( NTS ) |
| **Xcode Version:** | Version 8.0 (8A218a) |

**Output of gcc -v:**

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**

```
PHP 7.0.11 (cli) (built: Sep 16 2016 23:09:59) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10, Copyright (c) 1999-2016, by Zend Technologies
    with blackfire v1.12.0, https://blackfire.io, by Blackfireio Inc.
```

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by bocharsky-bw** [comment] 2016-09-20 09:40
Related discussion: https://github.com/ansible/ansible-modules-extras/issues/2935

**Comment by benjifisher** [comment] 2016-09-23 19:59
I just ran into this problem.  I am glad you tracked down the cause!

The problem is not the phar file, and I think you should update the title of this issue.  (I think I do not have permission to do that.)  The problem is that Homebrew uses a *shell* script as the composer executable:

```
$ ls -l /usr/local/bin/composer 
lrwxr-xr-x  1 bfisher  admin  37 Sep 17 10:44 /usr/local/bin/composer -> ../Cellar/composer/1.2.1/bin/composer
$ ls -l /usr/local/Cellar/composer/1.2.1/bin/composer 
lrwxr-xr-x  1 bfisher  admin  23 Sep 23 14:44 /usr/local/Cellar/composer/1.2.1/bin/composer -> ../libexec/composer
$ cat /usr/local/Cellar/composer/1.2.1/libexec/composer
#!/usr/bin/env bash
/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/composer/1.2.1/libexec/composer.phar "$@"
```

Ansible (and perhaps other tools) assume that the composer executable is a PHP script, which means that they can pass their own PHP configuration using `php -d ... composer`.

One solution is to turn that shell script into a PHP script.  I apologize for this incredible kludge, but it mostly works:  save this as `libexec/composer.php`:

```
#!/usr/bin/env php
<?php
array_shift($argv);
$arg_string = implode(' ', $argv);
passthru("/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/composer/1.2.1/libexec/composer.phar $arg_string", $return_var);
return $return_var;
```

and then make `bin/composer` a symbolic link to `../libexec/composer.php`.

I hope someone can do better than that.  Now, I can use Ansible's composer module.  The only problem I have noticed is that, when using composer directly (not via Ansible) I lose ASCII coloring.

I tried using something like this instead, but **this does not work**:

```
#!/usr/bin/env php
<?php
ini_set('allow_url_fopen', 'On');
ini_set('detect_unicode', 'Off');
require './composer.phar';
```

This almost works, but I could not figure out a way to discard the shebang line at the top of the phar file.

**Comment by bocharsky-bw** [comment] 2016-09-23 20:22
Hey @benjifisher , thank you for your investigating! I only tweaked the `libexec/composer.php` content as you said and it works for me now!

If this's the best solution we can find here - could you provide a PR for this to work out of the box, please?

**Comment by benjifisher** [comment] 2016-09-24 18:55
Let's give it a few days.  Maybe someone will come along with a variant of my last snippet that actually works.  If not, then I will submit a PR.

Meanwhile, how about changing the title of the issue as I suggested?  Something like "Brew provides shell script as composer executable, other tools expect a PHP script."

**Comment by josegonzalez** [comment] 2016-09-25 08:55
@benjifisher Can you just issue the pull request as is now? We can discuss whether there need to be any changes in the pull request.

**Comment by benjifisher** [comment] 2016-09-25 14:21
@josegonzalez:  done.

I do not know ruby, but it seems that I can override `AbstractPhpPhar::phar_wrapper` in the derived `Composer` class.  In the discussion above, I added `libexec/composer.php` and changed the symlink, but the PR simply replaces `libexec/composer`.

**Comment by bocharsky-bw** [comment] 2016-09-25 17:45
@benjifisher sorry for delay, I changed title - it's clearer now, thanks!

**Comment by javian** [comment] 2016-09-26 22:08
@bocharsky-bw the pr was just merged - can you give it a test run ?

**Comment by bocharsky-bw** [comment] 2016-09-27 06:28
@javian Yes! I give a test run from source and confirm that Composer with Ansible works now 👍 . Now I'm waiting when it will be released.

Thanks @benjifisher for this nice fix one more time!

**Comment by javian** [comment] 2016-09-27 06:29
@bocharsky-bw what do you mean by released ? The PR is merged now so it work on all systems that are up to date and using composer.

**Comment by bocharsky-bw** [comment] 2016-09-27 06:37
Ah, I thought I should test it by specifying Composer formula from source:
`$ brew install ~/www/libs/homebrew-php/Formula/composer.rb`

Anyway, I just upgraded Brew and reinstall Composer with `$ brew install composer` and it still works!

**Comment by bocharsky-bw** [comment] 2016-09-27 08:59
Hm, I think I found a problem after this merge. Now, when I use Composer without Ansible, i.e. just `$ composer install` - I don't see the original color scheme in the Composer's output, I mean Composer no longer support colors in its output out of the box 😞

@benjifisher Could your changes caused it?

**Comment by benjifisher** [comment] 2016-09-27 12:04
@bocharsky-bw:   Yes, I pointed out this defect in my first comment.  That is part of the reason I was hoping someone could suggest a better solution.  (The other part is that it just seems wrong to create a PHP script that uses `exec()` to call another PHP script.)

**Comment by peshi** [comment] 2016-10-01 11:37
borked ansi colors.. 👎

**Comment by javian** [comment] 2016-10-01 21:38
I'm guess it comes from the symfony/console module https://github.com/symfony/console/blob/b5044f6c999c0555fd2e7c889e8dc3f0246876de/Output/StreamOutput.php#L83-L105

**Comment by javian** [comment] 2016-10-04 20:56
The other option would be to force --ansi as one of the command line options in the script to get around it.

**Comment by bocharsky-bw** [comment] 2016-10-05 09:07
Hey @javian , good investigating!

I created #3675 to turn on Composer ANSI color by default.

**Comment by javian** [comment] 2016-10-05 20:25
I merged the ansi PR - @peshi give it another go now and it should work as expected.

**Comment by bocharsky-bw** [comment] 2016-10-05 20:57
@javian BTW, I had to reinstall composer formula to see color changes: simple `$ brew upgrade` have no effect. I suppose this is a normal behavior for Brew, right?

**Comment by peshi** [comment] 2016-10-07 09:47
Colors! Thanks for this! 👍

**Comment by benjifisher** [comment] 2016-10-07 12:15
@bocharsky-bw yes, that seems to be the normal behavior.  I guess that `brew upgrade` will work if the version number goes up, but does not trigger a reinstall when the formula is updated.

**Comment by bocharsky-bw** [comment] 2016-10-07 12:59
@benjifisher it makes sense, thanks for the clarification!

@javian I think we can close this issue, right?

**Comment by javian** [comment] 2016-10-07 13:48
@bocharsky-bw yup, the only thing left is to revision the formula to create a new bottle that will upgrade the installations.

**Comment by derimagia** [comment] 2016-10-16 04:50
Seems that this causes an issue where the php arguments are lost so you can't use aliases to disable xdebug for composer. I went back to the docs on composer and it  looks like it breaks the docs for xdebug since it says it's using homebrew for the examples: https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer

I think we should should be able to do this instead:

```php
Phar::loadPhar('/usr/local/Cellar/composer/1.2.1_1/libexec/composer.phar');
require 'phar://composer.phar/bin/composer';
```

**Comment by benjifisher** [comment] 2016-10-23 21:20
Thanks, that is what I was looking for in my first comment, when I suggested a PHP snippet that used `require` (but I could not get it to work).

We still want the two `ini_set()` lines from my snippet.  At least, we should not change the behavior unless we really mean to.

We do not want to hard-code the directory, so I used `__DIR__`.

With those changes, I think that the `composer` executable should look like this:

```php
#!/usr/bin/env php
<?php
ini_set('allow_url_fopen', 'On');
ini_set('detect_unicode', 'Off');
Phar::loadPhar(__DIR__ . '/composer.phar');
require 'phar://composer.phar/bin/composer';
```

I just submitted a PR to update the composer executable.  I have done a little testing.  (If you check out my branch, then `brew reinstall -s Formula/composer.rb` should do for further testing.)

- @bocharsky-bw, can you check that this version works with the Ansible composer module?
- @derimagia, does this solve the alias issues?

**Comment by derimagia** [comment] 2016-10-24 01:26
Looks good to me, and yeah I figured we wouldn't hard code that (was a POC). Also is the benefit of not forking to a new process which causes other issues and is why the script was using exec before.

Only thing I'd recommend would be that we probably would want to generalize if for other programs (See  work that @ablyler did https://github.com/Homebrew/homebrew-php/blob/32d11bf7eeb56fa455efaf600a9b06a49f67cf0b/Abstract/abstract-php-phar.rb)

**Comment by benjifisher** [comment] 2016-10-24 03:39
If I understand correctly, you are suggesting that we change `AbstractPhpPhar::phar_wrapper`.  Then every formula that extends `AbstractPhpPhar` will get a PHP script instead of a bash script, not just the formula for `composer` (unless the derived formula overrides the `phar_wrapper` method).

It seems reasonable to me, but I do not know this project well enough to be sure.

I just submitted a new PR that updates `AbstractPhpPhar::phar_wrapper` and removes the override from the `composer` formula.

**Comment by bocharsky-bw** [comment] 2016-10-26 12:54
Hey @benjifisher ,

Yes, this solution works fine with Ansible for me:
```php
#!/usr/bin/env php
<?php
ini_set('allow_url_fopen', 'On');
ini_set('detect_unicode', 'Off');
Phar::loadPhar(__DIR__ . '/composer.phar');
require 'phar://composer.phar/bin/composer';
```

**Comment by MikeMcQuaid** [comment] 2018-03-28 10:40
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json).

**Closed by MikeMcQuaid** 2018-03-28 10:40 UTC
Labels: help wanted
