### ISSUE TITLE
php56 --with-apache fails OS X 10.11.6

### ISSUE THREAD

**Issue by isghe** [Homebrew/homebrew-php#3629] opened 2016-09-27 10:52 UTC
## Description

`brew install php56 --with-apache`
fails with
`apxs:Error: Config file /usr/local/etc/apache2/2.4/httpd.conf not found.`

## Context and Logs
```
$ brew install php56 --with-apache
==> Installing php56 from homebrew/php
==> Downloading https://php.net/get/php-5.6.26.tar.bz2/from/this/mirror
Already downloaded: /Users/isghe/Library/Caches/Homebrew/php56-5.6.26
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.26_2 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-config-file-scan-dir=/usr/local/etc/php/5.6/conf.d --man
==> make
==> make install
Last 15 lines from /Users/isghe/Library/Logs/Homebrew/php56/03.make:
2016-09-27 12:19:27 +0200

make install

Installing PHP SAPI module:       apache2handler
/usr/local/Cellar/httpd24/2.4.23_1/build/instdso.sh SH_LIBTOOL='/usr/local/opt/apr/libexec/build-1/libtool' libs/libphp5.so /usr/local/Cellar/php56/5.6.26_2/libexec/apache2
/usr/local/opt/apr/libexec/build-1/libtool --mode=install install libs/libphp5.so /usr/local/Cellar/php56/5.6.26_2/libexec/apache2/
libtool: install: install libs/libphp5.so /usr/local/Cellar/php56/5.6.26_2/libexec/apache2/libphp5.so
Warning!  dlname not found in /usr/local/Cellar/php56/5.6.26_2/libexec/apache2/libphp5.so.
Assuming installing a .so rather than a libtool archive.
chmod 755 /usr/local/Cellar/php56/5.6.26_2/libexec/apache2/libphp5.so
apxs:Error: Config file /usr/local/etc/apache2/2.4/httpd.conf not found.
make: *** [install-sapi] Error 1
```

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.6
**Homebrew Version:**   | Homebrew 1.0.5
**PHP Version in use:** | 5.6
**Xcode Version:**      | Version 7.3.1 (7D1014)

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
-bash: /usr/local/bin/php: No such file or directory

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment] 2016-09-27 14:57
This is most likely due to a bug in the httpd24 bottle which was caused by brew. The httpd bottles are currently being regenerated and will be merged in  in a few hours.

**Comment by altrugon** [comment] 2016-09-27 17:00
Having the same problem than isghe, and I aslo have the same OS and configuration.

**Comment by javian** [comment] 2016-09-27 20:21
@altrugon the reason that the support for the apache that comes with osx was because we can't build the apache module on Sierra since the supporting scripts have been removed by Apple.

**Comment by javian** [comment] 2016-09-27 20:21
@isghe I just merged a new bottle for httpd24 can you see if you are still seeing the same issue ?

**Comment by esetnik** [comment] 2016-09-27 20:48
I'm seeing the same issue unfortunately

**Comment by esetnik** [comment] 2016-09-27 20:55
```==> Installing php56 from homebrew/php
==> Downloading https://php.net/get/php-5.6.26.tar.bz2/from/this/mirror
Already downloaded: /Users/ethan/Library/Caches/Homebrew/php56-5.6.26
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.26_2 --localstatedir=/usr/local/var
Last 15 lines from /Users/ethan/Library/Logs/Homebrew/php56/01.configure:
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for RAND_egd... no
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-php/issues

These open issues may also help:
Problem installing php56-redis https://github.com/Homebrew/homebrew-php/issues/3572
Updated php56-protobuf version. https://github.com/Homebrew/homebrew-php/pull/3272
php56 --with-apache fails OS X 10.11.6 https://github.com/Homebrew/homebrew-php/issues/3629
php56 failed to build on 10.11.5 https://github.com/Homebrew/homebrew-php/issues/3551
failed to install php56-pthreads https://github.com/Homebrew/homebrew-php/issues/2768
php56 failing with Incompatible library version: libphp5.so requires version 41.0.0 or later, but libpng16.16.dylib provides version 38.0.0 https://github.com/Homebrew/homebrew-php/issues/3602```

**Comment by javian** [comment] 2016-09-27 20:57
@esetnik that's a different issue not related - run `xcode-select --install` and it should restore the libz headers required to compile.

**Comment by esetnik** [comment] 2016-09-28 00:14
@javian thanks that suggestion worked. I guess the upgrade to sierra wiped out my xcode cli toolchain. Would you like me to delete my comments from this issue since my feedback was ultimately unrelated?

**Comment by isghe** [comment] 2016-09-28 00:20
@javian thanks a lot, the updated formula `homebrew/apache/httpd24` solved the problem, and I successfully installed `$ brew install php56 --with-apache` :-)

**Comment by javian** [comment] 2016-10-02 18:51
This issue has been corrected - closing.

**Closed by javian** 2016-10-02 18:51 UTC

**Comment by bydesignparis** [comment] 2016-11-06 07:44
I see this issue is closed but I still ran into the same issue as @altrugon on a fresh install of php56. On httpd relaunch I get 

`httpd: Syntax error on line 114 of /usr/local/etc/apache2/2.4/httpd.conf: Cannot load libexec/apache2/mod_log_config.so ...`

The fix as said is `brew uninstall httpd24`

**Comment by satyagv557** [comment] 2017-03-02 01:50
@javian: I have similar issue, using Sierra with Apache 2.2.31,  getting below error. 

httpd: Syntax error on line 122 of /Users/Shared/Development/env/local/cust/httpd-b2c/conf/httpd.conf: Cannot load /Users/Shared/Development/env/local/cust/httpd-b2c/modules/mod_rewrite.so into server: dlopen(/Users/Shared/Development/env/local/cust/httpd-b2c/modules/mod_rewrite.so, 10): Symbol not found: _apr_stat$INODE64\n  Referenced from: /Users/Shared/Development/env/local/cust/httpd-b2c/modules/mod_rewrite.so\n  Expected in: flat namespace\n in /Users/Shared/Development/env/local/cust/httpd-b2c/modules/mod_rewrite.so

my application runs in 2.2.31 only, we able to load it in El Captian, issue is in Sierra
