### ISSUE TITLE
phpXX compiles thread safe when using the --with-httpd option

### ISSUE THREAD

**Issue by Eydamos** [Homebrew/homebrew-php#4509] opened 2017-10-10 12:48 UTC
## Description

When using this command to install php `brew install php70 --with-httpd` the resulting php will be thread safe. I think this is the wrong behavior as the `--with-thread-safety` option is not set. This currently requires one to build all other modules (like php70-intl, php70-xdebug, php70-mcrypt etc.) to be installed with the `--build-from-source` option as they are not build with thread safety by default.

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | maxOS Sierra 10.12.4
**Homebrew version:**   | Homebrew 1.3.5
**PHP version in use:** | PHP 7.0.23
**Xcode version:**      | Xcode 9

**Output of `gcc -v`:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
PHP 7.0.23 (cli) (built: Oct  2 2017 16:15:18) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.23, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Comment by viktym** [comment] 2017-10-13 07:26
Have the same issue
It completely destroys my local dev environment
I need exactly NTS php
Some ETA when it can be fixed?

**Comment by javian** [comment] 2017-10-13 09:35
We are looking into it. This is caused by apache changing the default mpm from prefork to event so if you want to workaround the issue then change the apache config and php will adapt.

**Comment by viktym** [comment] 2017-10-13 11:59
@javian **brilliant solution**
Thanks a lot
You gave me back my faith in brew :)

**Comment by edrozenberg** [comment] 2017-10-16 15:41
I recompiled php after reinstalling httpd with the new httpd formulas.

The recompiled php automatically seems to use thread safety when I leave the default mod_mpm_event.so enabled in httpd.conf. I did NOT have to use ```--with-thread-safety``` php compile flag. phpinfo() shows:

```
Thread Safety       enabled
```

The thing to watch out for is homebrew bottled (pre-compiled) php extensions (phpXX-_____) are not thread safe, so installing any php extensions should be done with ```brew install --build-from-source phpXX-______```.

**Comment by jbiancot** [comment] 2017-10-18 04:23
I don't know who was the genius that came with the idea to replace the /etc/apache2 config for the /etc/httpd, because it F sucks. The /etc/apache2 and similar configration files follow the standard of Debian/Ubuntu which is over 65-70% of the linuxes on the net. The crap of RedHat/Centos is less than 25% and everyday losing more market share. I hope the same genius who decided to change and break the config will rectify and rollback. My 2 cents.

**Comment by javian** [comment] 2017-10-18 13:22
So, I just merged a fix that should for the compilation of non-threadsafe unless the option is given on the command line. Hopefully this should at least make the problem more appearant but lets see if we need to add additional texts to support this even further.

**Comment by javian** [comment] 2017-10-18 13:23
See #4533

**Comment by Eydamos** [comment] 2017-10-18 15:10
I can confirm that this fix works for php55, php56, php70, php71 and php72.

Thanks for the awesome work

**Closed** 2017-10-18 15:11 UTC
Labels: Bug
