### ISSUE TITLE
why auto install httpd , I only want upgrade php version to 7.2.3

### ISSUE THREAD

**Issue by cevin** [Homebrew/homebrew-php#4801] opened 2018-03-04 14:28 UTC
## Description

`brew upgrade` auto upgraded `php 7.2.1` to `php 7.2.3`, but auto installed httpd, apr, apr-util ... why?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.3
**Homebrew version:**   | Homebrew 1.5.8 & Homebrew/homebrew-core (git revision 44e6; last commit 2018-03-04)
**PHP version in use:** | 7.2.3
**Xcode version:**      | 9.2 & Build version 9C40b

**Output of `gcc -v`:**
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
> PHP 7.2.3 (cli) (built: Mar  2 2018 15:48:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies

**Build logs:** https://gist.github.com/49fff5e1ae54b59d88f44d6bc45a61ed

**Comment by alcaeus** [comment] 2018-03-05 05:50
Quoting @MikeMcQuaid [here](https://github.com/Homebrew/homebrew-core/issues/24654#issuecomment-369315125):
> It's a popular PHP option that we're building in by default as we're trying to reduce the number of options provided by formulae (as they are error prone and not tested by CI). It's not technically required but we require it. You can create your own PHP formula in your own tap if you'd rather build it differently.

**Comment by SMillerDev** [comment] 2018-03-05 07:49
This is a duplicate of https://github.com/Homebrew/homebrew-core/issues/24654 therefore closing this.

**Closed by SMillerDev** 2018-03-05 07:49 UTC

**Comment by MikeMcQuaid** [comment] 2018-03-06 19:25
This will not be installed any more if you use the bottle: https://github.com/Homebrew/homebrew-core/pull/24907
