### ISSUE TITLE
Installing php56-pthreads broke previously installed extensions

### ISSUE THREAD

**Issue by petitchevalroux** [Homebrew/homebrew-php#1910] opened 2015-07-15 17:17 UTC
With php56-redis previously installed, installing php56-phtreads broke the two following extensions : 
igbinary
redis

Here are the warning :
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-igbinary/igbinary.so' - dlopen(/usr/local/opt/php56-igbinary/igbinary.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php56-igbinary/igbinary.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-igbinary/igbinary.so' - dlopen(/usr/local/opt/php56-igbinary/igbinary.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-igbinary/igbinary.so
  Expected in: flat namespace
 in /usr/local/opt/php56-igbinary/igbinary.so in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-redis/redis.so' - dlopen(/usr/local/opt/php56-redis/redis.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-redis/redis.so
  Expected in: flat namespace
 in /usr/local/opt/php56-redis/redis.so in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-redis/redis.so' - dlopen(/usr/local/opt/php56-redis/redis.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-redis/redis.so
  Expected in: flat namespace
 in /usr/local/opt/php56-redis/redis.so in Unknown on line 0

------------------ | ------------------
**OS X Version:** | 0.10.4
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | 5.5.24
**Xcode Version:** | 6.4
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
**Output of php -v:** | PHP 5.5.24 (cli) (built: May 19 2015 10:10:05) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by petitchevalroux** [comment] 2015-07-15 17:20
I think this may be linked to the "with-thread-safety" needed by php56-pthreads

**Comment by ablyler** [comment] 2015-07-15 22:12
@petitchevalroux probably, what happens if you reinstall the other extensions?

**Comment by pcraum** [comment] 2015-07-16 08:12
output of brew uninstall php56-pthreads php56-redis php56-igbinary php56 && brew install php56-pthreads php56-redis && php -i | egrep Warning

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-redis/redis.so' - dlopen(/usr/local/opt/php56-redis/redis.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-redis/redis.so
  Expected in: flat namespace
 in /usr/local/opt/php56-redis/redis.so in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-redis/redis.so' - dlopen(/usr/local/opt/php56-redis/redis.so, 9): Symbol not found: _basic_globals

**Comment by petitchevalroux** [comment] 2015-07-16 08:13
Output of brew uninstall php56-pthreads php56-redis php56-igbinary php56 && brew install php56-pthreads php56-redis && php -i | egrep Warning

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-redis/redis.so' - dlopen(/usr/local/opt/php56-redis/redis.so, 9): Symbol not found: _basic_globals
  Referenced from: /usr/local/opt/php56-redis/redis.so
  Expected in: flat namespace
 in /usr/local/opt/php56-redis/redis.so in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-redis/redis.so' - dlopen(/usr/local/opt/php56-redis/redis.so, 9): Symbol not found: _basic_globals

**Comment by ablyler** [comment] 2015-07-17 01:47
What happens if you install the extension with the `--build-from-source` flag?

**Comment by pcraum** [comment] 2015-07-17 09:24
Hihi, new bug form php56-redis :
==> Downloading https://github.com/phpredis/phpredis/archive/2.2.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/php56-redis-2.2.7.tar.gz
==> /usr/local/opt/php56/bin/phpize
Error: No such file or directory - /usr/local/opt/php56-igbinary/include/igbinary.h

**Comment by petitchevalroux** [comment] 2015-07-17 09:25
Hihi, new bug from php56-redis :
==> Downloading https://github.com/phpredis/phpredis/archive/2.2.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/php56-redis-2.2.7.tar.gz
==> /usr/local/opt/php56/bin/phpize
Error: No such file or directory - /usr/local/opt/php56-igbinary/include/igbinary.h

**Comment by petitchevalroux** [comment] 2015-07-21 07:47
Last output is from brew install --build-from-source php56-pthreads php56-redis

**Comment by glassdimly** [comment] 2015-07-22 14:38
I can confirm this bug. I installed redis-server on top of php56 and whenever I run php cli commands I get 
```
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-igbinary/igbinary.so' - dlopen(/usr/local/opt/php56-igbinary/igbinary.so, 9): image not found in Unknown on line 0
```

**Comment by ivanbatic** [comment] 2015-08-01 18:17
+1

**Comment by glassdimly** [comment] 2015-08-01 19:43
I did a brew reinstall php56 and the problem is unsolved.

**Comment by ablyler** [comment] 2015-08-01 21:56
@petitchevalroux fix should be coming shortly

**Comment by ablyler** [comment] 2015-08-02 00:15
Merged a fix in, please try again.  Note you will need to build all php packages from source and not bottles after changing the threading option.

**Closed by ablyler** 2015-08-02 00:15 UTC

**Comment by petitchevalroux** [comment] 2015-08-03 11:31
php56-redis is now installable from source TY @ablyler

**Comment by glassdimly** [comment] 2015-08-03 20:27
Did a 
    brew remove php56-igbinary php56-redis 
    brew reinstall php56 --enable-maintainer-zts --build-from-source php56-igbinary --build-from-source php56-redis --build-from-source

Probably not concise but it worked. No more error. Thank you!

**Comment by johnlfoleyiii** [comment] 2015-11-17 19:27
Installing everything from source, starting with the version of php itself, has helped me solve a similar issue. In my instance, I reinstalled php56 from source with the necessary params '--enable-maintainer-zts --with-fpm --with-memcache --with-mcrypt --build-from-source', Then i reinstalled php56-pthreads from source, then I reinstalled all my other extensions from source and now I have everything working.

**Comment by erikhansen** [comment] 2016-01-05 16:38
I just ran into this issue and the commands that @glassdimly posted above fixed my issue:

```
brew remove php56-igbinary php56-redis 
brew reinstall php56 --enable-maintainer-zts --build-from-source php56-igbinary --build-from-source php56-redis --build-from-source
```

**Comment by AykutCevik** [comment] 2016-01-12 19:51
@glassdimly & @erikhansen 's solution worked for me. Thanks, had the same problem here.

**Comment by kwhat** [comment] 2016-01-27 23:00
So this is still an ongoing problem for me on 10.11 and this bug has been marked closed.  Please reopen this issue until the issue has been resolved.

**Comment by OGProgrammer** [comment] 2016-01-28 08:49
Def still an issue, either new issue or reopen this one? building from source seems to do the trick like @kwhat confirmed.

**Comment by naffan2014** [comment] 2016-02-02 08:18
first brew remove  php56-pthreads 
then brew install  php56-pthreads  --build-from-source
last brew install  php56-pthreads 

ok.
