### ISSUE TITLE
Failed to install php56-redis

### ISSUE THREAD

**Issue by danielcosta** [Homebrew/homebrew-php#1493] opened 2015-01-05 21:29 UTC
I`ve got an error when trying to install php56-redis.

```
$ brew install php56-redis
==> Installing php56-redis from homebrew/homebrew-php
==> Downloading https://github.com/phpredis/phpredis/archive/2.2.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/php56-redis-2.2.6.tar.gz
==> Patching
==> /usr/local/opt/php56/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php56-redis/2.2.6 --with-php-config=/usr/local/opt/php56/bin/php-config
==> make
static void redis_error_throw(char *err, size_t err_len TSRMLS_DC) {
^
4 errors generated.
make: *** [library.lo] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues
```

The required gist: https://gist.github.com/anonymous/19339c230973a919e9d4

**Comment by bycosta** [comment] 2015-01-05 21:33
Same here with php55-redis here! (Yosemite)

**Comment by tmoitie** [comment] 2015-01-07 10:18
Appears to have been introduced with #1485. Looks like all builds have been failing since that one was merged

**Comment by luyangx** [comment] 2015-01-13 10:56
Same here with php54-redis! (Yosemite) :)

**Comment by ShonM** [comment] 2015-01-29 15:17
Same with php56-redis with a fresh Yosemite, Homebrew, and Xcode install (latest of them all as of this comment)

**Comment by mkoczorowski** [comment] 2015-01-30 00:52
any workaround ?

**Comment by Lysrv-Jian** [comment] 2015-02-01 09:15
Same with me....Use "pecl install redis" instead of it.

**Comment by alanthing** [comment] 2015-02-02 15:06
@danielcosta Do you have the Xcode Command Line Tools up to date? I was able to install `php56-redis` without issue on a fully updated test system (fresh VM). The "[fatal error: 'ac_nonexistent.h' file not found](https://gist.github.com/anonymous/19339c230973a919e9d4#file-config-log-L117)" message seems to come from missing headers in the build environment. Everyone else commenting here has Yosemite too, but I can't reproduce. Maybe we can get to the bottom of it though...

Also, does including igbinary, ala `brew install -v php56-redis --with-igbinary`, produce different results or the same?

**Comment by danielcosta** [comment] 2015-02-03 12:26
Hey @alanthing the error is the same with `--with-igbinary`:

```
[danielcosta:~] $ brew install php56-redis --with-igbinary
==> Installing php56-redis from homebrew/homebrew-php
==> Downloading https://github.com/phpredis/phpredis/archive/2.2.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/php56-redis-2.2.6.tar.gz
==> /usr/local/opt/php56/bin/phpize
==> mkdir -p ext/igbinary
==> ./configure --prefix=/usr/local/Cellar/php56-redis/2.2.6 --with-php-config=/usr/local/opt/php56/bin/php-config --enable-redis-igbinary
==> make
static void redis_error_throw(char *err, size_t err_len TSRMLS_DC) {
^
4 errors generated.
make: *** [library.lo] Error 1
make: *** Waiting for unfinished jobs....
```

Raw gist-logs: https://gist.github.com/danielcosta/c32326bba3f79550f460

**Comment by jrschumacher** [comment] 2015-02-04 00:54
@alanthing I'm getting this when running the command

```
/private/tmp/php56-redis-eM0Te4/phpredis-2.2.6/library.c:83:51: error: expected expression
    if (redis_sock_write(redis_sock, cmd, cmd_len TSRMLS_DC) < 0) {
                                                  ^
/usr/local/Cellar/php56/5.6.5/include/php/Zend/../TSRM/TSRM.h:166:21: note: expanded from macro 'TSRMLS_DC'
#define TSRMLS_DC       , TSRMLS_D
                          ^
/usr/local/Cellar/php56/5.6.5/include/php/Zend/../TSRM/TSRM.h:165:18: note: expanded from macro 'TSRMLS_D'
#define TSRMLS_D        void ***tsrm_ls
                        ^
/private/tmp/php56-redis-eM0Te4/phpredis-2.2.6/library.c:188:55: error: too few arguments to function call, expected 2, have 1
        if (redis_sock->auth && resend_auth(redis_sock) != 0) {
                                ~~~~~~~~~~~           ^
/private/tmp/php56-redis-eM0Te4/phpredis-2.2.6/library.c:76:1: note: 'resend_auth' declared here
static int resend_auth(RedisSock *redis_sock TSRMLS_DC) {
^
/private/tmp/php56-redis-eM0Te4/phpredis-2.2.6/library.c:193:59: error: too few arguments to function call, expected 2, have 1
        if (redis_sock->dbNumber && reselect_db(redis_sock) != 0) {
                                    ~~~~~~~~~~~           ^
/private/tmp/php56-redis-eM0Te4/phpredis-2.2.6/library.c:49:1: note: 'reselect_db' declared here
static int reselect_db(RedisSock *redis_sock TSRMLS_DC) {
^
/private/tmp/php56-redis-eM0Te4/phpredis-2.2.6/library.c:353:49: error: too few arguments to function call, expected 3, have 2
            redis_error_throw(inbuf + 1, err_len);
            ~~~~~~~~~~~~~~~~~                   ^
/private/tmp/php56-redis-eM0Te4/phpredis-2.2.6/library.c:111:1: note: 'redis_error_throw' declared here
static void redis_error_throw(char *err, size_t err_len TSRMLS_DC) {
^
4 errors generated.
make: *** [library.lo] Error 1
make: *** Waiting for unfinished jobs....
couldn't understand kern.osversion `14.1.0'
```

**Comment by alanthing** [comment] 2015-02-16 21:02
Would you be able to try a re-install of the Command Line Tools package and install `php5x-redis` again? After searching a bit, it's in reference to missing headers that the compiler needs. Go to https://developer.apple.com/downloads/ and grab the package from there and give it a go and report back.

**Comment by jrschumacher** [comment] 2015-02-16 21:33
@alanthing I re installed the tools and still have the error:

```
> $ brew install php56-redis                                          [±master]
==> Installing php56-redis from homebrew/homebrew-php
==> Downloading https://github.com/phpredis/phpredis/archive/2.2.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/php56-redis-2.2.6.tar.gz
==> /usr/local/opt/php56/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php56-redis/2.2.6 --with-php-config=/
==> make
static void redis_error_throw(char *err, size_t err_len TSRMLS_DC) {
^
4 errors generated.
make: *** [library.lo] Error 1
make: *** Waiting for unfinished jobs....
couldn't understand kern.osversion `14.1.0'
```

**Comment by shadowhand** [comment] 2015-02-27 21:27
I'm getting similar errors with `brew install php56-opcache`, it fails on `make`:

```
==> ./configure --prefix=/usr/local/Cellar/php56-opcache/7.0.4 --with-php-config=/usr/local/opt/php56/bin/php-config
==> make
         ^
1 error generated.
make: *** [zend_accelerator_module.lo] Error 1
1 error generated.
make: *** [ZendAccelerator.lo] Error 1

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/
```

**Comment by alanthing** [comment] 2015-03-10 00:47
I was able to build 2.2.6 again on a clean system without build issues. But, 2.2.7 is out, so I updated to that and was also able to build it cleanly. We're now using bottles by default, so unless you need a specific compile option and build from source, and you're using the PHP 5.x bottle, you should have no trouble with the updated formula.

The PRs are queued for testing; I'll update this issue tomorrow once things are pushed through.

**Comment by alanthing** [comment] 2015-03-10 14:12
New versions pushed. Please try the new bottled version. If you have trouble and are not using a bottled version of the main `php5x` formulas, please reinstall PHP using a bottle. I'm closing this issue for now, but feel free to comment if issues with `php5x-redis` persist and we can re-open.

If you're having issues with any formula other than `php5x-redis`, do not comment here; open a new issue please.

**Closed by alanthing** 2015-03-10 14:12 UTC

**Comment by danielcosta** [comment] 2015-03-10 19:15
It worked, thank you!

**Comment by frumbert** [comment] 2017-08-22 03:00
`brew install php56-redis` seemed to be going well for me (MacOS Sierra), told me it worked, and then i tried to restart my apache - ` sudo apachectl restart`.

    Password:
    httpd: Syntax error on line 177 of /usr/local/etc/apache2/2.4/httpd.conf: Cannot load /usr/local/lib/libphp5.so into server: dlopen(/usr/local/lib/libphp5.so, 10): Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
    Referenced from: /usr/local/lib/libphp5.so\n  Reason: image not found

So I went and had a look there - sure enough, libjpeg.8.dylib has been upgraded to libjpeg.8.dylib and is gone. I wondered if I should try copying it back in from the `/usr/local/Cellar/jpeg/8d/lib` but I don't know how this stuff works.

Why did installing redis have to recompile libpng and libjpeg? I don't know.

Here's a pastebin of the whole output: https://pastebin.com/Sz2zLyNq
