### ISSUE TITLE
php71 alpha version gets installed by default instead of stable php70

### ISSUE THREAD

**Issue by yesenarman** [Homebrew/homebrew-php#3349] opened 2016-07-11 01:27 UTC
## Description

If I have no php installed and then try to install a package which depends on php, php71 gets chosen by homebrew, but I expect it to chose php70 since it is the latest stable version.
This might be an intended behavior, so I'm not sure.

## Example

I have none of the php versions from homebrew installed on my system. I then run:
```brew install hombrew/php/php-code-sniffer```
Since `php-code-sniffer` depends on php, homebrew automatically installs `php71` package.

## Possible reason

If it is not an intended behavior, it seems that the problem might be in these lines of code from `PhpMetaRequirement`:
```ruby
  if $supported_php_versions.nil?
    $supported_php_versions = %w{php53 php54 php55 php56 php71 php70}
  end

  if Formula["php53"].linked_keg.exist? && $supported_php_versions.include?('php53')
    default_formula "php53"
  elsif Formula["php54"].linked_keg.exist? && $supported_php_versions.include?('php54')
    default_formula "php54"
  elsif Formula["php55"].linked_keg.exist? && $supported_php_versions.include?('php55')
    default_formula "php55"
  elsif Formula["php56"].linked_keg.exist? && $supported_php_versions.include?('php56')
    default_formula "php56"
  elsif Formula["php70"].linked_keg.exist? && $supported_php_versions.include?('php70')
    default_formula "php70"
  elsif Formula["php71"].linked_keg.exist? && $supported_php_versions.include?('php71')
    default_formula "php71"
  else
    default_formula $supported_php_versions.last
  end
```
Initially `$supported_php_versions` is a list of `["php53", "php54", "php55", "php56", "php71", "php70"]`, but then every time when `Formula["php??"]` gets accessed, since php formulas extend  `AbstractPhp` , this line from `AbstractPhp` gets called:
```ruby
  # Force all php meta requiprements to use this version
  $supported_php_versions = [self.name.split("::")[2].downcase]
```
which overrides `$supported_php_versions`. Since none of the linked kegs exists, the last `else` clause gets executed, but by that time `$supported_php_versions = ["php71"]`, so the `last` method returns php71 version.

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11.5
**Homebrew Version:**   | 0.9.9
**Xcode Version:**      | 7.3.1

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP 5.5.34 (cli) (built: Apr 22 2016 19:16:58)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by javian** [comment] 2016-07-14 07:50
Thanks for the feedback @yesenarman ! I believe @ablyler made the last changes to these lines of code - can you comment on this Andy ?

**Comment by MikeLund** [comment] 2016-08-05 07:10
@ablyler ?

==> Upgrading homebrew/php/phpdocumentor
==> Installing dependencies for homebrew/php/phpdocumentor: php71
==> Installing homebrew/php/phpdocumentor dependency: php71
Error: Cannot install homebrew/php/php71 because conflicting formulae are installed.

  php70: because different php versions install the same binaries.

Please `brew unlink php70` before continuing.


Very annoying and unintended behavior!

**Comment by javian** [comment] 2016-08-05 07:31
I'm working on a fix for this.

**Comment by javian** [comment] 2016-08-08 21:04
This should do the trick.

**Closed** 2016-08-08 21:04 UTC
