### ISSUE TITLE
Incompatible library version: libphp5.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

### ISSUE THREAD

**Issue by benstinton** [Homebrew/homebrew-php#2508] opened 2015-11-09 16:52 UTC
After installing brew php55 and restarting Apache with:
sudo apachectl -e info -k restart

I get:
httpd: Syntax error on line 173 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php55/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php55/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: /usr/local/opt/php55/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

I have seen other post this fault as well and whilst some possible issues and fixes are discussed there is nothing that seems to work for me. Any help would be much appreciated?

**OS X Version:** | 10.11.1
**Homebrew Version:** | 0.9.5
**PHP Version in use:** | 5.5.30
**Xcode Version:** | 7.1
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

**Output of php -v:** | Failed loading /usr/local/Cellar/php55/5.5.29_3/lib/php/extensions/no-debug-non-zts-20121212/opcache.so:  dlopen(/usr/local/Cellar/php55/5.5.29_3/lib/php/extensions/no-debug-non-zts-20121212/opcache.so, 9): image not found
PHP 5.5.29 (cli) (built: Nov  9 2015 16:40:54) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

**Comment by ablyler** [comment] 2015-11-15 14:02
@benstinton it looks like in your php config it is referencing an old version of opcache:

```
Failed loading /usr/local/Cellar/php55/5.5.29_3/lib/php/extensions/no-debug-non-zts-20121212/opcache.so: dlopen(/usr/local/Cellar/php55/5.5.29_3/lib/php/extensions/no-debug-non-zts-20121212/opcache.so, 9): image not found
```

I bet fixing that will fix the other issues.

**Comment by benstinton** [comment] 2015-11-16 11:23
@ablyler  I had the issue before I tried a few different things and that warning showed up. I have removed the old reference, and that still hasn't fixed the underlying issue. I have even tried installing homebrew apache as referenced in some other threads, but still get the issue. Thanks for the idea Andy, but is there anything else I can do?

**Comment by benstinton** [comment] 2015-11-16 11:43
@ablyler At this point is there a fail safe method as I'm losing some time on a project. i.e. Should revert to a fresh install of OSX Yosemitie?

**Comment by estchlos** [comment] 2015-11-17 09:58
For last couple days I was having the same problem and today I finally solved it. The problem is not in PHP but in Apache 2.4 that is distributed with OSX. The way to solve it is to install apache from brew. What you have to do is simply:

Set up path variables for new apache installation: 

    echo "export PATH=\$(echo \$PATH | sed 's|/usr/local/bin||; s|/usr/local/sbin||; s|::|:|; s|^:||; s|\(.*\)|/usr/local/bin:/usr/local/sbin:\1|')" >> ~/.bash_profile && source ~/.bash_profile

Unload old apache:

    sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist 2>/dev/null    

Install apache from brew:

    brew install httpd24

Set up apache to start on boot

    ln -sfv $(brew --prefix httpd22)/homebrew.mxcl.httpd24.plist ~/Library/LaunchAgents
 
    launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.httpd24.plist

An reboot the system. After the reboot go to the terminal and do:

    sudo apachectl -k restart

If apache should restart and show you errors if there are any but error about wrong version of libxml2.2.dylib will be gone.

After that your system will be using apache from brew and all updates will also came from brew. In the future if you will update to the next version of OSX that will be after El Capitan, the system may go back to original apache, if that will happen simply reinstall apache again.

**Comment by benstinton** [comment] 2015-11-18 16:43
@estchlos Thank-you so much for trying to help. 
Unfortunately I was running out of time so I had to take the nuclear option before I could try your solution. 
I reinstalled OS-X Yosemite and got things set up perfectly, then upgraded to El Capitan and after reverting to the previous httpd.conf everything is working as expected

Should I close the issue?

**Comment by estchlos** [comment] 2015-11-19 09:12
Thats cool that your solved the problem. Are you on latest version of El Capitan (10.11.1)? I am asking because apache was working fine for me when I was on vanilla 10.11.0 but after update I had to reinstall httpd from brew.

**Comment by benstinton** [comment] 2015-11-19 09:51
I'm using 10.11.1 and apache shipped with OSX is working

**Comment by cytopia** [comment] 2015-12-02 17:05
I am at El Capitan (10.11.1) using PHP 5.6.16 and OSX stock apache.
I can confirm the problem.

**Comment by alxvallejo** [comment] 2015-12-03 18:01
@estchlos - Don't you have to set all your modules in your apache config?

**Comment by benstinton** [comment] 2015-12-04 13:11
I have this issue again now on El Capitan

**Comment by alxvallejo** [comment] 2015-12-04 18:29
Alright so the issue I had for the outdated libxml2 package was to make sure that brew update was running correctly. Do you get any errors from running that? If not, try brew upgrade <package> and that did it for me.

**Comment by estchlos** [comment] 2015-12-09 11:28
@benstinton @alxvallejo on my home mac since 10.9 I am using apache from brew and never had the problem. Only recently when I've got new mac at work with 10.10 and 10.11 after that, this issue showed up. From my perspective the best bet is to install apache from brew, you will have faster updates and will be independent from Apple "little" issues like this one.

I don't remember exactly what I did with modules in apache config but I either moved config from original apple installation or used default one with some fixes to my needs.

**Comment by jeremybradbury** [comment] 2016-02-05 23:46
+1!

This isn't preventing me from running apache, however when I try to `brew upgrade` i get this:

`Upgrading homebrew/php/composer
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib
  Referenced from: /usr/local/bin/php`

I am not at all running php 54, I am running 56, so my file at this location is named: /usr/local/opt/icu4c/lib/libicui18n.56.dylib

Here is the exact entry from my terminal 
`
brew upgrade
==> Upgrading 13 outdated packages, with result:
homebrew/php/composer 1.0.0-alpha11, dnsmasq 2.75, homebrew/php/drush 8.0.2, git 2.7.0, homebrew/apache/httpd22 2.2.31, danpoltawski/mdk/moodle-sdk 1.5.3, mysql 5.7.10, node 5.5.0, homebrew/php/php56 5.6.18, homebrew/php/phpmyadmin 4.5.4, pv 1.6.0, tig 2.1.1, homebrew/php/wp-cli 0.22.0
==> Upgrading homebrew/php/composer
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.54.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
composer: PHP Phar support is required for this formula
Error: An unsatisfied requirement failed this build.
`
This is the first time running update/upgrade since upgrading to El Capitan (10.11.2).

I know this isn't **exactly** the same issue, but it seems have the same root problem: incorrect version references for dynamic libraries (dylibs are like DLLs). Hopefully this helps shed light on the issue.

**Comment by jeremybradbury** [comment] 2016-02-06 00:11
I was able to get beyond this by removing behat (which had unresolvable dependancies), and installing php-mcrypt (which brew doctor told me was a required dependency although had been working fine).

Again, possibly **unrelated**, yet hopefully helpful.

Homebrew used to be very clear about how to resolve issues and could be trusted to run `brew update` then `brew upgrade` without worrying about anything. Now it seems like it sends everyone on a wild goose chase, not explaining the problem, and taking down dev servers. Sad day! =/

**Comment by SamirBoulil** [comment] 2016-02-16 12:27
Hello,

I confirm I have the same issue here with stock apache.

```
$ apachectl -v
Server version: Apache/2.4.16 (Unix)
Server built:   Jul 31 2015 15:53:26
```
and php56 installed from homebrew :
```
$ php -v
PHP 5.6.13 (cli) (built: Feb 16 2016 13:24:48) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

When I reload Apache:
```
$ apachectl -t
httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

Did anyone find a solution ?

**Comment by ajarzebowski** [comment] 2016-02-16 12:36
Have you tried my solution with reinstalling apache trough brew? It's working for me since I had the problem.

**Comment by SamirBoulil** [comment] 2016-03-02 14:26
@ajarzebowski No, I use OSX's stock apache. Can't seem to make brew apache work in my setup. It keeps giving me 403 permission denied.

**Comment by azulkipli** [comment] 2016-03-04 00:21
I got this issue too,

In terminal I checked php -c
PHP 5.6.18 (cli) (built: Mar  4 2016 06:52:31) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

But when I update default el capitan apache2 httpd.conf load php5 module to brew path
"/usr/local/Cellar/php56/5.6.18/libexec/apache2/libphp5.so"
got this
``
$ sudo apachectl -k restart                                          [7:02:09]
httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/Cellar/php56/5.6.18/libexec/apache2/libphp5.so into server: dlopen(/usr/local/Cellar/php56/5.6.18/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib\n  Referenced from: /usr/local/Cellar/php56/5.6.18/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
``
Please help

**Comment by adrazich** [comment] 2016-04-05 13:39
Hi, I'm getting this error too. I installed this without issues on my laptop a few months ago. I just got a new work computer and am having issues getting it setup.

It's complaining about my libxml2 being incompatible using version 10.0.0 but it's actually running libxml2 version 12.3.0 and requires version 12.0.0.

I've tried updating homebrew, uninstalling libxml2, unlinking it, reinstalling and relinking it. But, I still have the same issue.

Here's what it looks like:
![screen shot 2016-04-05 at 9 35 13 am](https://cloud.githubusercontent.com/assets/1614075/14283594/f21a401e-fb11-11e5-91ce-7c3f4522a308.png)

Other info:
- php : 5.6.20
- apache - 2.4.18
- el capitan - 10.11.4

**Comment by javian** [comment] 2016-04-05 17:02
It looks like the stock libxml library in El Capitan is providing libxml10.0

```
otool -L /usr/lib/libxml2.2.dylib
/usr/lib/libxml2.2.dylib:
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 55.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

There was a solution to a similar problem provided here https://github.com/Homebrew/homebrew-php/issues/419#issuecomment-11424345 which makes sense since the envvars script only loads libraries in `/usr/lib/`which could explain why it doesn't find the homebrewed library. Could you try working around that @adrazich and see if it works ?

**Comment by javian** [comment] 2016-04-05 17:10
In the brewed version of Apache it has changed the envvars script to read 
```
if test "x$DYLD_LIBRARY_PATH" != "x" ; then
  DYLD_LIBRARY_PATH="/usr/local/Cellar/httpd24/2.4.18/lib:$DYLD_LIBRARY_PATH"
else
  DYLD_LIBRARY_PATH="/usr/local/Cellar/httpd24/2.4.18/lib"
fi
export DYLD_LIBRARY_PATH
```
so I'm pretty sure this is the cause but I haven't been able to test it yet.

**Comment by adrazich** [comment] 2016-04-05 20:07
@javian That fixed my issue. It's not complaining at all anymore.

**Comment by javian** [comment] 2016-04-09 13:39
@benstinton can you try the fix mentioned towards the end of this post if you are still having the issue ?

**Comment by tarunhere** [comment] 2016-07-15 14:59
@ajarzebowski  I tried your steps, but then my current sites stopped working. I also changed the path in new httpd.conf file to "/Library/WebServer/Documents" but still my old sites were not accessible. I checked log but no luck.

So I reverted the brew httpd24 package. Now again, I am getting old error as below:

httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php56/libexec/apache2/libphp5.so

Please help my localhost is down and I'm not able to work.

**Comment by maxsky** [comment] 2016-09-22 06:45
@ajarzebowski 

1. Install apache from brew:

beforce install you should do `brew tap homebrew/apache`.

2. Set up apache to start on boot:

If you wanna apache httpd start on boot, the command is

```
sudo brew services start httpd24
```

3. Reboot the system. After the reboot go to the terminal and do:

Now, just reboot and review process **httpd** is running. Don't have to do `sudo apachectl -k restart` command.

**Comment by javian** [comment] 2016-09-22 06:53
@tarunhere you should be able to get around that by install php from source and using the `--without-ldap` option.

Example `brew install -s php56 --without-ldap`

**Comment by josegonzalez** [comment] 2016-09-25 08:48
Seems like this issue is "resolved" and everyone has a fix. Closing

**Closed by josegonzalez** 2016-09-25 08:48 UTC
