### ISSUE TITLE
php70 installed with lots of warnings

### ISSUE THREAD

**Issue by markl181** [Homebrew/homebrew-php#4732] opened 2018-01-27 23:13 UTC
## Multiple warnings on install of php70

I used brew install php70 --with-httpd to install php70. Originally I tried brew install php70 however this appeared to completely skip installing the php7.so folder, so I removed php70 and php56, then reinstalled with the httpd option. The install generated a lot of warnings that it said should be reported. I then installed oauth, imagick and xdiff with php70. 

When I now go to start php, I get the following error. I'm not sure if this is an issue with the xdiff extension or with the warnings in the php70 install. The extensions directory named in the message does not exist, however there is an xdiff directory at /usr/local/Cellar/php70-xdiff. I tried uninstalling xdiff and restarting apache, however I still get the same error. 

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.27_19/lib/php/extensions/no-debug-non-zts-20151012/xdiff.so' - dlopen(/usr/local/Cellar/php70/7.0.27_19/lib/php/extensions/no-debug-non-zts-20151012/xdiff.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.27_19/lib/php/extensions/no-debug-non-zts-20151012/xdiff.so' - dlopen(/usr/local/Cellar/php70/7.0.27_19/lib/php/extensions/no-debug-non-zts-20151012/xdiff.so, 9): image not found in Unknown on line 0

## Context and Logs

Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

==> ./configure --prefix=/usr/local/Cellar/php70/7.0.27_19 --localstatedir=/usr/
==> make
==> make install
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:648:in `plist'
Please report this to the homebrew/php tap!

Parameter | Value
--------- | ------------------
**Mac OS 10.13.2**       | _your macOS version (output of `sw_vers -productVersion`)_
**Homebrew version: 1.5.2**   | _your Homebrew version (output of `brew --version`)_
**PHP version in use: 7.0** | _your PHP version (output of `/path/to/php -v`)_
**Xcode version: 9.2**      | _your Xcode version (output of `xcodebuild -version`)_

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.27_19/lib/php/extensions/no-debug-non-zts-20151012/xdiff.so' - dlopen(/usr/local/Cellar/php70/7.0.27_19/lib/php/extensions/no-debug-non-zts-20151012/xdiff.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.27_19/lib/php/extensions/no-debug-non-zts-20151012/xdiff.so' - dlopen(/usr/local/Cellar/php70/7.0.27_19/lib/php/extensions/no-debug-non-zts-20151012/xdiff.so, 9): image not found in Unknown on line 0
PHP 7.0.27 (cli) (built: Jan 27 2018 15:50:36) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

**Build logs:** https://gist.github.com/275c75117762f8b041c4600bb031b7b6

**Comment by markl181** [comment] 2018-01-28 13:23
I tried rolling back to php56, but that also doesn't work. When I try to install it, I get 'Error: /usr/local/opt/php56 is not a valid keg'

**Comment by SMillerDev** [comment] 2018-01-29 09:33
Thanks for the detailed report!
It seems to be a duplicate of #4722 though, so I'll close this one and you can read the other issue for the options to remedy this.

**Closed by SMillerDev** 2018-01-29 09:33 UTC
