### ISSUE TITLE
Unloading of php-fpm launchagent fails

### ISSUE THREAD

**Issue by mariusvw** [Homebrew/homebrew-php#2483] opened 2015-10-29 11:27 UTC
When trying to unload the plist file it runs into an error, resulting not being able to stop php-fpm

```
$ launchctl unload homebrew.mxcl.php56.plist
/Users/mariusvw/homebrew/Cellar/php56/5.6.14/homebrew.mxcl.php56.plist: Could not find specified service
```

For now I use the following workaround to stop php-fpm:

```
pkill php-fpm
```

**Comment by javian** [comment] 2016-04-26 03:24
@mariusvw did you manage to resolve this issue ?

**Comment by mariusvw** [comment] 2016-04-28 09:26
I have two options:

1. add -F to the plist file (I prefer this, since the -F causes php-fpm to ignore the daemonize option)
2. add daemonize to the php-fpm configuration.

I currently use this and so far my tests run it seems to work fine.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/> 
  <key>Label</key>
  <string>homebrew.mxcl.php56</string>
  <key>ProgramArguments</key>
  <array> 
    <string>/Users/mariusvw/homebrew/opt/php56/sbin/php-fpm</string>
    <string>-F</string>
    <string>--fpm-config</string>
    <string>/Users/mariusvw/homebrew/etc/php/5.6/php-fpm.conf</string>
  </array>
  <key>RunAtLoad</key>
  <true/> 
  <key>LaunchOnlyOnce</key>
  <true/> 
  <key>UserName</key>
  <string>mariusvw</string>
  <key>WorkingDirectory</key>
  <string>/Users/mariusvw/homebrew/var</string>
  <key>StandardOutPath</key>
  <string>/Users/mariusvw/homebrew/opt/php56/var/log/php-fpm.log</string>
  <key>StandardErrorPath</key>
  <string>/Users/mariusvw/homebrew/opt/php56/var/log/php-fpm.log</string>
</dict>
</plist>
```

**Comment by gjuric** [comment] 2016-08-22 15:16
The same thing is happening on PHP 7.0

~~~
launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.php70.plist
launchctl: Error unloading: homebrew.mxcl.php70
~~~

**Comment by josegonzalez** [comment] 2016-09-25 08:49
@mariusvw Can you make a pull request for that? Otherwise, I'll be closing this issue in 2 weeks.

**Comment by mariusvw** [comment] 2016-10-04 08:41
@josegonzalez done, tested it again, same change still works.

**Comment by javian** [comment] 2016-10-04 20:07
The default config file should contain `deamonize = no` as a default so I wonder why that isn't picked up. The PR you provided does the same thing but as an argument when launching.

**Comment by javian** [comment] 2016-10-04 20:14
I can't reproduce this error on my machine. @mariusvw can you check that your php-fpm.conf contains the daemonize setting ?

**Comment by javian** [comment] 2016-10-04 20:19
Once the service is running can you issue `launchctl list homebrew.mxcl.php56` and paste the output ?

**Comment by mariusvw** [comment] 2016-10-04 21:11
Adding the following to php-fpm.conf resolves one part of the issue:

```
daemonize = no
```

However, since this should always be the right setting to have with homebrew while using launchctl I thought it would be a better place to add it to the plist file with:

```
<string>--nodaemonize</string>
```

Adding the no daemonize option didn't resolve the problem completely.
After removing the following option the startup and shutdown of php-fpm works as expected:

```
<key>LaunchOnlyOnce</key>		
<true/>
```

The launchctl output:

```
% launchctl list homebrew.mxcl.php56
{
	"LimitLoadToSessionType" = "Aqua";
	"StandardErrorPath" = "/Users/mariusvw/homebrew/opt/php56/var/log/php-fpm.log";
	"Label" = "homebrew.mxcl.php56";
	"TimeOut" = 30;
	"OnDemand" = false;
	"LastExitStatus" = 0;
	"PID" = 72855;
	"Program" = "/Users/mariusvw/homebrew/opt/php56/sbin/php-fpm";
	"ProgramArguments" = (
		"/Users/mariusvw/homebrew/opt/php56/sbin/php-fpm";
		"--nodaemonize";
		"--fpm-config";
		"/Users/mariusvw/homebrew/etc/php/5.6/php-fpm.conf";
	);
};
```

**Comment by javian** [comment] 2016-10-13 19:11
Do you know why the LaunchOnlyOnce needs to be removed ?

**Comment by mariusvw** [comment] 2016-10-13 19:17
In case PHP-fpm crashes it wont get restarted if LaunchOnlyOnce is there.

**Comment by javian** [comment] 2016-10-13 20:00
Looking at the manual it seems like a bad option for fpm indeed
```
     LaunchOnlyOnce <boolean>
     This optional key specifies whether the job can only be run once and only once.  In other words,
     if the job cannot be safely respawned without a full machine reboot, then set this key to be
     true.
```

**Comment by javian** [comment] 2016-10-13 20:08
I was looking back through the commit logs and found this https://github.com/Homebrew/homebrew-php/issues/370 which is the issue where LaunchOnlyOnce was added so according to that we should not remove it.

**Comment by mariusvw** [comment] 2016-11-23 14:12
Updated the code, adding the --nodaemonize resolves the issue when the config does not contains daemonize = no.

**Closed** 2017-03-25 17:13 UTC
Labels: 2 Week Notice
