### ISSUE TITLE
cannot install php71 : missing libsystem_darwin.dylib (Xcode 9)

### ISSUE THREAD

**Issue by theredled** [Homebrew/homebrew-php#4590] opened 2017-11-21 15:16 UTC
## Description

I can't install php71 with `brew install php71 --with-httpd` as an error appears during the `make` process : 
> ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64

Full log :

> ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
> make: *** [sapi/cgi/php-cgi] Error 1
> make: *** Waiting for unfinished jobs....
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [libs/libphp7.bundle] Error 1
> ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
> ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [sapi/fpm/php-fpm] Error 1
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [sapi/cli/php] Error 1

Seems like that file doesn't exist anymore in XCode 9; which is a shame because Brew asked me to install Xcode 9 or it wouldn't work...

Any idea?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.6
**Homebrew version:**   | 1.3.8
**PHP version in use:** | 7.1.8
**Xcode version:**      |  9.1

**Output of `gcc -v`:**

> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 9.0.0 (clang-900.0.38)
> Target: x86_64-apple-darwin16.7.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
>   Referenced from: /usr/local/opt/php71-intl/intl.so
>   Reason: image not found in Unknown on line 0
> 
> Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
>   Referenced from: /usr/local/opt/php71-intl/intl.so
>   Reason: image not found in Unknown on line 0
> PHP 7.1.8 (cli) (built: Aug  8 2017 18:49:37) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
>     with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Comment by SMillerDev** [comment] 2017-11-21 16:19
did you install the command line tools after installing xcode 9? Because this looks like an issue with the command line tools.

**Comment by theredled** [comment] 2017-11-21 16:24
Yes I did:
> $ xcode-select --install
> xcode-select: error: command line tools are already installed, use "Software Update" to install updates
> $ xcode-select -v
> xcode-select version 2347.

**Comment by theredled** [comment] 2017-11-22 02:03
All right, I stopped adding `--with-httpd` as it seems to be included by default as `brew install php71` says: 

> With the release of macOS Sierra the Apache module is now not built by default.

It installs without any error but `libphp7.so` can't be found... Where is it supposed to be ?

**Comment by gzilt** [comment] 2017-11-22 06:16
I have the same problem as @theredled. Installing with `--with-httpd` has error. Doing it without` --with-httpd` success but no `libphp7.so`

**Comment by SMillerDev** [comment] 2017-11-22 09:57
This thread seems to resolve around the same issue, and it seems to be caused by the users setup
https://github.com/unbit/uwsgi/issues/1364#issuecomment-340961420

Maybe that could work? I just tried to install `--with-httpd` just now, and it worked fine in my environment.

**Comment by Finetuned** [comment] 2017-11-22 14:26
Does [`this solution`](https://forums.developer.apple.com/thread/87829) shed any light?

**Comment by theredled** [comment] 2017-11-22 16:50
Works fine with XCode 8.3.3. The problem seems to be Sierra + XCode 9.
But `git doctor` now complains - which is a way more minor issue.

**Comment by tomyates** [comment] 2017-11-23 13:27
Anyone know of a solution which doesn't involved downgrading Xcode 9?

**Comment by SMillerDev** [comment] 2017-11-23 15:52
There's one in the thread I linked

**Comment by Finetuned** [comment] 2017-11-23 16:21
Can you be specific about which one you are referring to?

**Comment by tomyates** [comment] 2017-11-23 16:50
@SMillerDev Thanks. None of that seems to work for me.

**Comment by dknell** [comment] 2017-11-26 01:27
I just did a clean install of MacOS Sierra (10.12.6) and had this same issue. I installed homebrew before Xcode was fully downloaded. I noticed that homebrew downloaded and installed the command line tools itself. I'm not sure if that's was caused the problem, but here's how I fixed it:

- Removed the command line tools
```
sudo rm -rf /Library/Developer/CommandLineTools
```

- Reinstalled the command line tools via xcode
```
xcode-select --install
```

- Set the correct path
```
xcode-select -s /Library/Developer/CommandLineTools
```

- Then the php7 install works fine
```
brew install php71 --with-httpd
```

**Comment by gakkispy** [comment] 2017-11-26 13:54
Thanks @dknell ! It works for me.

**Comment by wikusv** [comment] 2017-11-30 05:17
Thanks @dknell worked for me

**Comment by ajielee** [comment] 2017-11-30 21:58
Thanks @dknell and @barryp, [these steps](https://github.com/Homebrew/homebrew-php/issues/4590#issuecomment-346977512) works but just don't forget to use `sudo` in the 3rd step.

**Comment by javian** [comment] 2017-12-02 09:28
I'm currently committing a fix so that it should work on Sierra again. It is also required for creating the bottles for the new PHP releases including 7.2 so this has to work.

**Comment by javian** [comment] 2017-12-03 22:20
The fix has been merged. Closing issue.

**Closed by javian** 2017-12-03 22:20 UTC

**Comment by kevinquillen** [comment] 2018-03-09 14:49
Only thing that worked for me was the steps from @dknell.
