### ISSUE TITLE
Cannot install homebrew/php/php55-mcrypt

### ISSUE THREAD

**Issue by realriot** [Homebrew/homebrew-php#1658] opened 2015-04-13 13:02 UTC
Install is aborted with:

[...]
==> Installing php55-mcrypt from homebrew/homebrew-php
==> Installing dependencies for php55-mcrypt: php55, mhash, mcrypt
==> Installing php55-mcrypt dependency: php55
==> Downloading https://www.php.net/get/php-5.5.23.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php55-5.5.23
==> ./configure --prefix=/opt/local/Cellar/php55/5.5.23 --localstatedir=/opt/local/var --sysconfdir=/opt/local/etc/php/5.5 --with-config-file-path=/opt/local/etc/php/5.5 --
checking for gzgets in -lz... yes
checking whether to enable bc style precision math functions... yes
checking for BZip2 support... yes
checking for BZip2 in default path... not found
configure: error: Please reinstall the BZip2 distribution

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

**Comment by armybean** [comment] 2015-04-13 17:39
Same here:

```
☁  ~  brew install php56 --with-thread-safety
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://www.php.net/get/php-5.6.7.tar.bz2/from/this/mirror
######################################################################## 100,0%
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.7 --localstatedir=/usr/loca
checking for gzgets in -lz... yes
checking whether to enable bc style precision math functions... yes
checking for BZip2 support... yes
checking for BZip2 in default path... not found
configure: error: Please reinstall the BZip2 distribution

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues
```

**Comment by armybean** [comment] 2015-04-13 17:51
I just executed `xcode-select --install` and now, PHP 5.6 installs like a charm. :)

**Comment by cmckni3** [comment] 2015-04-25 19:21
Duplicate of https://github.com/Homebrew/homebrew-php/issues/309

**Comment by alanthing** [comment] 2015-04-30 14:33
We should put something like the following on the main readme...

There seem to be some inconsistencies between the compiler tools and libraries that come with full Xcode versus the command line tools package. I'd recommend enforcing that you are using the CLT version of the tools:

```
xcode-select --install
sudo xcode-select --switch /Library/Developer/CommandLineTools
```

**Closed by alanthing** 2015-04-30 14:33 UTC
