### ISSUE TITLE
Can't connect to Localhost after installing PHP7

### ISSUE THREAD

**Issue by DaveyJake** [Homebrew/homebrew-php#2672] opened 2015-12-13 10:51 UTC
I'm running `Homebrew 0.9.5 (git revision d4cf; last commit 2015-12-13)` on `OS X 10.11.2` and can no longer connect to my Mac's built-in `localhost` server.  Google Chrome says the `webpage is not available: ERR_CONNECTION_REFUSED`.

This is the error message I get when running the `sudo apachectl -t` command in Terminal:

````
httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php70/libexec/apache2/libphp7.so into server: dlopen(/usr/local/opt/php70/libexec/apache2/libphp7.so, 10): Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib
Referenced from: /usr/local/opt/php70/libexec/apache2/libphp7.so
Reason: Incompatible library version: libphp7.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
````

When running the `otool -L /usr/local/opt/php70/libexec/apache2/libphp7.so` command in Terminal I am told `/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.3.0)`.

Has anyone else encountered this error and/or know any remedies? I don't want to have to downgrade back to `php56` but I might just have to.  Here's the complete terminal message regarding `libphp7.so`:

```
/usr/local/opt/php70/libexec/apache2/libphp7.so:
	/usr/lib/libaprutil-1.0.dylib (compatibility version 4.0.0, current version 4.0.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 216.4.0)
	/usr/lib/libapr-1.0.dylib (compatibility version 5.0.0, current version 5.8.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libexslt.0.dylib (compatibility version 9.0.0, current version 9.15.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.4.0)
	/usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 36.0.0, current version 36.0.0)
	/usr/local/opt/jpeg/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.3.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/local/opt/freetype/lib/libfreetype.6.dylib (compatibility version 19.0.0, current version 19.0.0)
	/usr/local/opt/unixodbc/lib/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

Any advice would be greatly appreciated!

**UPDATE**: Rechecked my `$PATH` and made sure it was set to `$(brew --prefix Cellar/php70/7.0.0)/bin:$PATH`; Decided to install the PHP7 `next stable` package from <a href="http://php-osx.liip.ch/">`php-osx.liip.ch`</a> as I know it installs additional helpful extensions.  Installed it directly to `/usr/local/` all while not changing my $PATH.  Not sure what did it but now everything is working as expected.  Any ideas?

**Comment by javian** [comment] 2016-04-09 14:27
This is caused by the envvars script which loads the xml dylib in /usr/lib instead of /usr/local/lib - there is a longer issue description here . https://github.com/Homebrew/homebrew-php/issues/2508 . Are you able to test it @DaveyJake ?

**Comment by hongchangfirst** [comment] 2016-06-25 05:40
I also met this problem, when I restart apache, it says: httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load libexec/apache2/libphp7.so into server: dlopen(/usr/libexec/apache2/libphp7.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/libexec/apache2/libphp7.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/libexec/apache2/libphp7.so

Not sure if the libphp.so is right or some other dependencies is missing.

**Comment by tryfinding** [comment] 2016-07-22 11:31
same error :


apachectl configtest                                                                                                                                              [19:30:35]
httpd: Syntax error on line 175 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php70/libexec/apache2/libphp7.so into server: dlopen(/usr/local/opt/php70/libexec/apache2/libphp7.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/opt/php70/libexec/apache2/libphp7.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php70/libexec/apache2/libphp7.so

**Comment by xstoop** [comment] 2016-08-12 12:17
I also met this problem:
sudo apachectl -t:
httpd: Syntax error on line 170 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php70/libexec/apache2/libphp7.so into server: dlopen(/usr/local/opt/php70/libexec/apache2/libphp7.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/opt/php70/libexec/apache2/libphp7.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php70/libexec/apache2/libphp7.so

My system is OS X Yosemite 10.10.5

**Comment by javian** [comment] 2016-08-12 12:33
@xstoop that's a different problem which you can find the solution to in another issue https://github.com/Homebrew/homebrew-php/issues/3074

**Comment by josegonzalez** [comment] 2016-09-25 08:26
Closing as there hasn't been any response in 2+ weeks.

**Closed by josegonzalez** 2016-09-25 08:26 UTC
